import createClient from 'openapi-fetch';
import type { Client } from 'openapi-fetch';
import { ENV } from '@paima/sdk/utils';

// generated by openapi-typescript
import type { paths as GameRestPaths } from './rest-schema.js';

export function getGameRestClient(): Client<GameRestPaths> {
  return createClient<GameRestPaths>({ baseUrl: ENV.BACKEND_URI });
}
export const gameRestClient = getGameRestClient();
