log_level = "info"
http_server_host = "0.0.0.0"
http_server_port = 7007

secret_key = { seed = "avail" }
port = 37000

full_node_ws = ["ws://node:9944"]
app_id = 1
confidence = 92.0
block_processing_delay = 0
sync_start_block = 0

bootstraps = ["/dns4/lightbootstrap/tcp/39000/p2p/12D3KooWStAKPADXqJ7cngPYXd2mSANpdgh1xQ34aouufHA2xShz"]
