export class Name {
  static shortWallet(wallet: string) {
    // if starts with 0x then 6 chars
    const chars = wallet.startsWith('0x') ? 6 : 4;
    return `${wallet.substring(0, chars)}...${wallet.substring(
      wallet.length - 4
    )}`;
  }

  static generateName(wallet: string) {
    // convert wallet to a number
    let hash = 0;
    for (let i = 0; i < wallet.length; i++) {
      const char = wallet.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash |= 0; // Convert to 32bit integer
    }
    const first = Math.abs(hash) % Name.nouns.length;
    const second = Math.abs(hash) % Name.adjectives.length;
    return `${Name.adjectives[second]} ${Name.nouns[first]}`.toLocaleLowerCase();
  }

  private static nouns = [
    'aardvark',
    'Acanthus',
    'Aconite',
    'adder',
    'Ageratum',
    'agouti',
    'albatross',
    'alligator',
    'Allium',
    'Almond',
    'Aloe',
    'alpaca',
    'Alyssum',
    'Amaranth',
    'Amaryllis',
    'Amur Adonis',
    'anaconda',
    'anchovies',
    'anemone',
    'angelfish',
    'angler',
    'angora goat',
    'ant',
    'anteater',
    'antelope',
    'ape',
    'Apple',
    'Apricot',
    'Arbutus',
    'archerfish',
    'armadillo',
    'Artichoke',
    'Asparagus',
    'Aster',
    'Astilbe',
    'Astragalus',
    'auk',
    'Avocado',
    'axolotl',
    'aye-aye',
    'baboon',
    'backswimmer',
    'badger',
    'Bamboo',
    'Banana',
    'bandicoot',
    'banshee',
    'Barberry',
    'Bark',
    'barnacle',
    'barracuda',
    'Basil',
    'basilisk',
    'basking shark',
    'bass',
    'bat',
    'beagle',
    'Bean',
    'bear',
    'beaver',
    'bee',
    'Bee Balm',
    'beetle',
    'Beetroot',
    'behemoth',
    'Bellflower',
    'Berry',
    'betta',
    'bigfoot',
    'Bindweed',
    'bison',
    'bittern',
    'Blackberry',
    'Blanketflower',
    'blister beetle',
    'blobfish',
    'bloodhound',
    'Blossom',
    'Bluebeard',
    'Bluebell',
    'Blueberry',
    'bluefish',
    'Bluestem',
    'boa',
    'boar',
    'bobcat',
    'bogeyman',
    'bongo',
    'Bottlebrush',
    'Boxwood',
    'Breech',
    'brittle star',
    'Broccoli',
    'Brussel',
    'Bryony',
    'Buckbean',
    'budgie',
    'buffalo',
    'Bugleweed',
    'Bugloss',
    'bull',
    'bullfrog',
    'bumblebee',
    'Bunchberry',
    'bunny',
    'Bupleurum',
    'Burdock',
    'Buttercup',
    'butterfly',
    'Cabbage',
    'Cactus',
    'caiman',
    'Caladium',
    'calf',
    'Calibrachoa',
    'camel',
    'Campion',
    'Canaigre Dock',
    'Candytuft',
    'capybara',
    'caracal',
    'Carambola',
    'caribou',
    'Carnation',
    'carp',
    'Carrot',
    'Carthamus',
    'Castor Bean',
    'cat',
    'Catchfly',
    'caterpillar',
    'catfish',
    'Catmint',
    'Catnip',
    'Cattail',
    'Celery',
    'centipede',
    'cerberus',
    'Chalkstick',
    'chameleon',
    'champ',
    'Checkerbloom',
    'cheetah',
    'Cherry',
    'chicken',
    'Chicory',
    'chihuahua',
    'Chili',
    'chimera',
    'chimpanzee',
    'chinchilla',
    'chipmunk',
    'Chives',
    'chupacabra',
    'cicada',
    'Cinquefoil',
    'clam',
    'Clematis',
    'Clianthus',
    'Clover',
    'clownfish',
    'cobra',
    'cockatoo',
    'cockatrice',
    'cockroach',
    'Coconut',
    'cocoon',
    'codfish',
    'collie',
    'Comfrey',
    'Coneflower',
    'Copao',
    'coral',
    'Coreopsis',
    'Corn',
    'Corydalis',
    'Cosmos',
    'Cotoneaster',
    'cougar',
    'Courgette',
    'cow',
    'Cowberry',
    'coyote',
    'crab',
    'crane',
    'Cranesbill',
    'crayfish',
    'Cress',
    'cricket',
    'crocodile',
    'Crocus',
    'Croton',
    'crow',
    'cub',
    'cuckoo',
    'Cucumber',
    'Currant',
    'cuscus',
    'cuttlefish',
    'Cyclamen',
    'cyclops',
    'Cymbidium',
    'Cyperus',
    'dachshund',
    'dalmatian',
    'deer',
    'Delphinium',
    'Dendrobium',
    'devon rex',
    'Dianthus',
    'dik-dik',
    'dingo',
    'Dodder',
    'dodo',
    'dog',
    'Dogbane',
    'Dogwood',
    'dolphin',
    'donkey',
    'doodle',
    'dormouse',
    'dove',
    'dragon',
    'dragonfish',
    'dragonfly',
    'droid',
    'drum fish',
    'duck',
    'dung beetle',
    'eagle',
    'earthworm',
    'echidna',
    'Echinacea',
    'Echinops',
    'Edelweiss',
    'eel',
    'Eggplant',
    'Elderberry',
    'elephant',
    'elk',
    'emu',
    'Epimedium',
    'Eremurus',
    'Eucalyptus',
    'Eupatorium',
    'fairy',
    'falcon',
    'faun',
    'fennec',
    'Fennel',
    'fenrir',
    'ferret',
    'Fescue',
    'Fiddleneck',
    'Fig',
    'Filaree',
    'firefly',
    'fish',
    'flamingo',
    'Flax',
    'flea',
    'Fleabane',
    'Floss',
    'flounder',
    'fly',
    'fossa',
    'fox',
    'foxcat',
    'Foxglove',
    'Foxtail',
    'frog',
    'frogfish',
    'Galanthus',
    'Galax',
    'Garland',
    'gazelle',
    'gecko',
    'Gentian',
    'Geranium',
    'Geum',
    'ghost',
    'ghoul',
    'giant',
    'gibbon',
    'Ginger',
    'giraffe',
    'Gladiolus',
    'glider',
    'gnat',
    'goat',
    'goblin shark',
    'Goldenrod',
    'goldfish',
    'golem',
    'goliath frog',
    'goose',
    'Goosefoot',
    'gopher',
    'gorgon',
    'gorilla',
    'goshawk',
    'gosling',
    'Grape',
    'grasshopper',
    'greyhound',
    'griffin',
    'grizzly',
    'groundhog',
    'grouper',
    'guinea pig',
    'hammerhead shark',
    'hamster',
    'hare',
    'Harlequin',
    'harpy eagle',
    'harrier',
    'hawk',
    'Hawthorn',
    'Hazel',
    'Hazelnut',
    'Heartleaf',
    'hedgehog',
    'Hedysarum',
    'Helenium',
    'Heliotrope',
    'Hellebore',
    'hellhound',
    'Hemp',
    'hen',
    'Herb',
    'heron',
    'Hibiscus',
    'Hippeastrum',
    'hippogriff',
    'hippopotamus',
    'Hogbean',
    'Hollowroot',
    'Hollyhock',
    'Hornbeam',
    'hornbill',
    'hornet',
    'horse',
    'horsefly',
    'horseshoe crab',
    'Hosta',
    'hound',
    'housefly',
    'howler',
    'hummingbird',
    'husky',
    'Hyacinth',
    'hydra',
    'hyena',
    'Hypericum',
    'Hyssop',
    'Iberis',
    'ibex',
    'ibis',
    'iguana',
    'Impatien',
    'Ivy',
    'jackal',
    'jackalope',
    'jackdaw',
    'Jackfruit',
    'jackrabbit',
    'jaguar',
    'jay',
    'jellyfish',
    'Kalanchoe',
    'Kale',
    'Kanawao',
    'kangaroo',
    'kingfisher',
    'kite',
    'kitten',
    'kiwi',
    'koala',
    'koi fish',
    'kraken',
    'krill',
    'Laburnum',
    'ladybird',
    'ladybug',
    'lamb',
    'Lamium',
    'Larch',
    'Larkspur',
    'Lathyrus',
    'Laurel',
    'Leadwort',
    'Leeks',
    'lemming',
    'Lemon',
    'Lemon balm',
    'lemur',
    'leopard',
    'leprechaun',
    'Lettuce',
    'Leucothoe',
    'leviathan',
    'liger',
    'Lime',
    'Limonium',
    'lion',
    'Lisianthus',
    'lizard',
    'llama',
    'lobster',
    'loch nessy',
    'locust',
    'Lotus',
    'lovebird',
    'Lucerne',
    'Lungwort',
    'Lupine',
    'lynx',
    'macaw',
    'mackerel',
    'Madder',
    'Madwort',
    'maggot',
    'magpie',
    'maine coon',
    'Mallow',
    'mammoth',
    'manatee',
    'Manchineel',
    'Mandarin',
    'Mandevil',
    'Mandrake',
    'Mango',
    'manticore',
    'mantis',
    'Maple',
    'marmot',
    'Masterwort',
    'Mazus',
    'meerkat',
    'Melon',
    'Mezereon',
    'Milfoil',
    'Milkweed',
    'millipede',
    'Mink',
    'minotaur',
    'Mint',
    'mite',
    'moa',
    'mockingbird',
    'mole',
    'mongoose',
    'monkey',
    'Monkshood',
    'moon',
    'moorhen',
    'moose',
    'mosquito',
    'Moss',
    'moth',
    'mouse',
    'Mugwort',
    'Mulberry',
    'mule',
    'Mullein',
    'Muscar',
    'Mushroom',
    'muskox',
    'muskrat',
    'Myrtle',
    'narwhal',
    'Nasturtium',
    'Nectarine',
    'Nerine',
    'Nettle',
    'newt',
    'nightingale',
    'nutria',
    'nymph',
    'ocelot',
    'octopus',
    'ogre',
    'okapi',
    'Oleander',
    'Olive',
    'Onion',
    'opossum',
    'Orange',
    'orangutan',
    'orb weaver',
    'orca',
    'Orchid',
    'Oregano',
    'ostrich',
    'otter',
    'owl',
    'ox',
    'oyster',
    'Panakenake',
    'panda',
    'pangolin',
    'panther',
    'Papaya',
    'papillon',
    'parakeet',
    'parrot',
    'Pea',
    'Peach',
    'peacock',
    'Pear',
    'pegasus',
    'pelican',
    'penguin',
    'Penstemon',
    'Pepper',
    'Pepperbush',
    'Peppermint',
    'pheasant',
    'Philodendron',
    'Phlox',
    'phoenix',
    'pigeon',
    'piglet',
    'Pine',
    'Pineapple',
    'Pinwheel',
    'piranha',
    'pit bull',
    'Pittosporum',
    'pixie',
    'platypus',
    'Pleurothallis',
    'Plum',
    'Plumbago',
    'polecat',
    'Polemonium',
    'Pomegranate',
    'poodle',
    'Poplar',
    'Poppy',
    'porcupine',
    'possum',
    'Potato',
    'prawn',
    'Privet',
    'puffer',
    'puffin',
    'pug',
    'puma',
    'Pumpkin',
    'puppy',
    'Purslane',
    'python',
    'quagga',
    'Quince',
    'quokka',
    'rabbit',
    'Rabbitbrush',
    'raccoon',
    'Radish',
    'ragdoll',
    'ram',
    'Ranunculus',
    'Raspberry',
    'rat',
    'rattlesnake',
    'raven',
    'Reed',
    'reindeer',
    'Restharrow',
    'rhinoceros',
    'Rhizomes',
    'Rhododendron',
    'Rice',
    'robin',
    'robot',
    'Rockcress',
    'roe deer',
    'rooster',
    'rottweiler',
    'Rover',
    'Rue',
    'Sage',
    'Salal',
    'salamander',
    'Salix',
    'salmon',
    'Saltbush',
    'satyr',
    'savannah cat',
    'sawfish',
    'Saxifrage',
    'Scabiosis',
    'scarab beetle',
    'scorpion',
    'seagull',
    'seahorse',
    'seal',
    'Sedge',
    'Senecio',
    'serpent',
    'serval',
    'Shamrock',
    'shark',
    'sheep',
    'shrimp',
    'siamang',
    'Silverberry',
    'Silverweed',
    'skunk',
    'sloth',
    'slug',
    'snail',
    'snake',
    'Snapdragon',
    'Snowbell',
    'Snowberry',
    'Snowdrop',
    'Sorrel',
    'Southernwood',
    'sparrow',
    'Speedwell',
    'sphinx',
    'spider',
    'Spiderwort',
    'Spinach',
    'Sprout',
    'squid',
    'Squill',
    'squirrel',
    'starfish',
    'Starfruit',
    'starling',
    'Statice',
    'stingray',
    'Stonecress',
    'Stonecrop',
    'stork',
    'Strawberry',
    'sturgeon',
    'Sundew',
    'Sundrops',
    'sunfish',
    'Sunflower',
    'swallow',
    'swan',
    'Sweetgrass',
    'swordfish',
    'tadpole',
    'tapir',
    'tarantula',
    'tasmanian devil',
    'termite',
    'tetra',
    'Thistle',
    'Thorn',
    'Thornapple',
    'thunderbird',
    'Thyme',
    'tiger',
    'tigon',
    'toad',
    'toadfish',
    'Toadflax',
    'Tomato',
    'tortoise',
    'toucan',
    'trixie',
    'troll',
    'trout',
    'Trunk',
    'tsetse fly',
    'Tuberose',
    'tuna',
    'turkey',
    'Turnip',
    'turtle',
    'Twinspur',
    'unicorn',
    'urchin',
    'Vine',
    'viper',
    'vulture',
    'vywern',
    'walkingstick',
    'wallaby',
    'Walnut',
    'walrus',
    'wasp',
    'Watermelon',
    'weasel',
    'werewolf',
    'whale',
    'Willow',
    'wolf',
    'wolfdog',
    'wolffish',
    'wolverine',
    'wombat',
    'woodpecker',
    'Woodruff',
    'Woodrush',
    'worm',
    'yak',
    'Yarrow',
    'yeti',
    'Yucca',
    'zebra',
    'zebu',
    'zombie',
    'zonkey',
    'zorse',
    'Zucchini',
  ];
  private static adjectives = [
    '32-bit',
    '64-bit',
    'abandoned',
    'aberrant',
    'abiding',
    'able',
    'able-bodied',
    'abnormal',
    'abominable',
    'aboriginal',
    'abrasive',
    'abrupt',
    'absent',
    'absentminded',
    'absolute',
    'absolute unbiased',
    'absolute unit of',
    'abstract',
    'absurd',
    'abundant',
    'abusive',
    'abysmal',
    'abyssal',
    'academic',
    'acceptable',
    'accessible',
    'accidental',
    'acclaimed',
    'accommodating',
    'accomplished',
    'accountable',
    'accumulated',
    'accurate',
    'accursed',
    'accusative',
    'accused of being',
    'acerbic',
    'achievable',
    'aching',
    'acidic',
    'acknowledged',
    'acme-invented',
    'acoustic',
    'acrobatic',
    'activated',
    'actual',
    'acute',
    'adamant',
    'adaptative',
    'addictive',
    'additional',
    'additive',
    'adept',
    'adequate',
    'adherent',
    'adhesive',
    'adiabatic',
    'adjacent',
    'adjustable',
    'administrative',
    'admirable',
    'adoptable',
    'adorable',
    'adorned',
    'adrenalized',
    'adult',
    'advanced',
    'advantageous',
    'adversarial',
    'advisable',
    'aerial',
    'aesthetic',
    'affectionate ',
    'affiliated',
    'affirmative',
    'afflicted',
    'affordable',
    'aforementioned',
    'ageless',
    'aggravating',
    'aggressive',
    'agile',
    'aging',
    'agitated',
    'aglow',
    'agreeable',
    'agricultural',
    'ahistorical',
    'aimless',
    'airborne',
    'airless',
    'airlike',
    'airsick',
    'airtight',
    'airworthy',
    'airy',
    'alabaster',
    'alacritous',
    'alarming',
    'albino',
    'alert',
    'algebraic',
    'alien',
    'alienated',
    'alight',
    'aligned',
    'alive',
    'alkaline',
    'all-around',
    'all-purpose',
    'all-seeing',
    'all-too-common',
    'alleged',
    'allegiant',
    'allergenic',
    'allergic',
    'allocable',
    'allotted',
    'alluring',
    'allusive',
    'almost',
    'aloof',
    'alpha',
    'alphabetical',
    'alterable',
    'alternative to',
    'altruistic',
    'amaranthine',
    'amateur',
    'amazing',
    'amazonian',
    'amber',
    'ambidextrous',
    'ambient',
    'ambiguous',
    'ambitious',
    'ambivalent',
    'ambulatory',
    'amenable',
    'amethyst',
    'amiable ',
    'amoeboid',
    'amoral',
    'amorous',
    'amorphous',
    'amphibian',
    'ample',
    'amusing',
    'analogous',
    'analphabetic',
    'analytic',
    'analyzable',
    'ancestral',
    'ancient',
    'anecdotal',
    'anemic',
    'angelic',
    'angered',
    'angular',
    'animalistic',
    'animated',
    'anime',
    'annotated',
    'annoying',
    'annual',
    'anonymous',
    'another',
    'antagonistic',
    'anthropomorphic',
    'anti-corrosive',
    'anticipated',
    'anticlimactic',
    'antiheroic',
    'antiquated',
    'antiseptic',
    'antisocial',
    'antsy',
    'anxious',
    'apathetic',
    'apex',
    'apocalyptic',
    'apolitical',
    'apologetic',
    'appalling',
    'apparent',
    'appealing',
    'appeasing',
    'appetizing',
    'applauding',
    'applicative',
    'applied',
    'appreciative',
    'apprehensive',
    'approachable by',
    'appropriate',
    'approved',
    'approving',
    'approximate',
    'aquamarine',
    'aquaphobic',
    'aquatic',
    'arbitrary',
    'arboreal',
    'arcade',
    'archaic',
    'architectural',
    'arctic',
    'ardent',
    'argentic',
    'arguable',
    'argumentative',
    'arid',
    'aristocratic',
    'aristotelean',
    'arithmetic',
    'armed',
    'armored',
    'army',
    'aromatic',
    'arresting',
    'arrogant',
    'artful',
    'articulated',
    'artificial',
    'artistic',
    'ascendant',
    'ascetic',
    'ashamed',
    'ashy',
    'asocial',
    'aspectual',
    'aspherical',
    'asphyxiated',
    'aspiring',
    'assertive',
    'assignable',
    'assistant',
    'assistive',
    'associate',
    'assorted',
    'assuring',
    'astonishing',
    'astounding',
    'astronomical',
    'asymmetrical',
    'athletic',
    'atlantic',
    'atomic',
    'atonal',
    'atrocious',
    'attachable',
    'attack',
    'attractive',
    'attributable',
    'atypical',
    'audacious',
    'auditory',
    'augmented',
    'august',
    'auric',
    'authentic',
    'authoritarian',
    'autobiographical',
    'autographed',
    'automated',
    'autonomous',
    'auxiliary',
    'available',
    'avant-garde',
    'avenging',
    'average',
    'aversive',
    'avian',
    'avid',
    'avionic',
    'avoidable',
    'awakened',
    'awesome ',
    'awful',
    'awkward',
    'axial',
    'axiomatic',
    'azimuthal',
    'azonal',
    'azure',
    'babbling ',
    'baboonish',
    'babylonian',
    'backbreaking',
    'backed',
    'backhanded',
    'backless',
    'backmost',
    'backstage',
    'backstairs',
    'backwards',
    'bacteriological',
    'bacteriophagous',
    'bad',
    'badass',
    'baked',
    'balanced ',
    'bald ',
    'ballistic',
    'bamboozled',
    'banal',
    'bankrupt',
    'banned',
    'bannered',
    'barbaric',
    'bare-footed',
    'barefoot',
    'barehanded',
    'bareheaded',
    'baritone',
    'barometric',
    'baroque',
    'barotropic',
    'barred',
    'barren',
    'barycentric',
    'basalt',
    'base',
    'based',
    'bashful ',
    'basic',
    'bathymetric',
    'battered',
    'battleful',
    'batwing',
    'beaded',
    'beardless',
    'beastly',
    'beatific ',
    'beautiful',
    'bedless',
    'beefy ',
    'befitting ',
    'befuddled ',
    'beguiling ',
    'behavioristic',
    'belated',
    'believable ',
    'bellyless',
    'beloved ',
    'belowground',
    'bended',
    'benedictive',
    'beneficial',
    'benevolent',
    'bengal',
    'berserk',
    'best',
    'best kind of',
    'betrayed',
    'betraying',
    'better ',
    'bewildered',
    'bewitched',
    'bewitching ',
    'biannual',
    'biased',
    'biaxial',
    'bibliophilic',
    'bicolored',
    'bicorned',
    'bidirectional',
    'bifurcated',
    'big brain',
    'big-hearted ',
    'bilateral',
    'bilingual',
    'billionaire',
    'bimetallic',
    'bimonthly',
    'binary',
    'binaural',
    'binding',
    'binocular',
    'biochemical',
    'biodegradable',
    'biogenetic',
    'biographical',
    'biological',
    'bioluminescent',
    'bionic',
    'biosynthetic',
    'bipedal',
    'birch',
    'birthday',
    'biting',
    'bitter',
    'bittersweet',
    'bizarre',
    'bladelike',
    'blameless',
    'blameworthy',
    'bland',
    'blank',
    'blazing',
    'bleak',
    'blessed ',
    'blinding',
    'blinking',
    'blissful',
    'blonde ',
    'bloodless',
    'bloodthirsty',
    'bloody',
    'blooming',
    'blue-eyed',
    'blunt ',
    'blurry',
    'blushing ',
    'boastful',
    'bobtailed',
    'bodacious ',
    'bodyless',
    'bogus',
    'bohemian ',
    'boiled',
    'boisterous ',
    'bold',
    'bombastic',
    'bombproof',
    'boneless',
    'boolean',
    'boomerang',
    'booming',
    'bootstrapped',
    'borderless',
    'borderline',
    'borealis',
    'bored',
    'bossy',
    'botanical',
    'bothersome',
    'bouncy',
    'boundless ',
    'bountiful ',
    'boxing',
    'bracing ',
    'braggy',
    'braided',
    'brainwashed',
    'brainy',
    'brave',
    'breakneck',
    'breathtaking',
    'brief ',
    'bright ',
    'brilliant',
    'brisk ',
    'brittle ',
    'broadminded ',
    'broken',
    'brokenhearted ',
    'bronze',
    'brotherly ',
    'brown',
    'bruised',
    'brunette',
    'brutal',
    'buffed',
    'buffoonish',
    'bugged',
    'bulky ',
    'bulletproof',
    'bullying',
    'bumpy ',
    'buoyant ',
    'burdenless',
    'bureaucratic',
    'burning',
    'busybodied',
    'butterfly-effective',
    'buxom ',
    'buzzing ',
    'bystander',
    'cacophonic',
    'cadastral',
    'cadaverous',
    'caesarian',
    'caged',
    'cagey',
    'calamitous',
    'calculated',
    'calligraphic',
    'callous',
    'calming',
    'calorific',
    'camel case',
    'camouflaged',
    'cancelled',
    'candescent',
    'candid',
    'candy',
    'canned',
    'canny',
    'canonised',
    'cantankerous',
    'capable ',
    'capacious',
    'capricious',
    'capsulated',
    'captain',
    'captivating',
    'caramel',
    'carbon-dated',
    'carbonated',
    'cardboard',
    'cardinal',
    'carefree',
    'careful',
    'careless',
    'caring',
    'carnal',
    'carnival',
    'carnivorous',
    'carribean',
    'carsick',
    'cartesian',
    'cartoon',
    'cased',
    'castled',
    'casual',
    'casuistic',
    'cataclysmic',
    'catacombic',
    'catapulted',
    'catastrophic',
    'catchable',
    'catchy',
    'categoric',
    'cathartic',
    'caustic',
    'cautious',
    'cavalier',
    'cave',
    'ceaseless',
    'celebrated',
    'celestial',
    'cellular',
    'celtic',
    'centered',
    'ceramic',
    'cereal',
    'cerebral',
    'ceremonial',
    'certain',
    'certified',
    'chainsaw',
    'chalky',
    'challenging',
    'champion',
    'changeless',
    'chanting',
    'chaotic',
    'chaotic evil',
    'chaotic good',
    'chaotic neutral',
    'characteristic',
    'charging',
    'charismatic',
    'charitable ',
    'charming',
    'chatty',
    'cheap',
    'cheating',
    'cheeky',
    'cheerful',
    'cheering',
    'cheerless',
    'cheesy',
    'chemical',
    'cherished',
    'chestnut',
    'chewable',
    'chic',
    'chief',
    'childish',
    'chilling',
    'chinless',
    'chiromantic',
    'chirping',
    'chitinous',
    'chivalrous',
    'choleric',
    'chonky',
    'christmas',
    'chromed',
    'chronic',
    'chthonic',
    'chubby',
    'chuffed',
    'chummy',
    'chunky',
    'circular',
    'civil',
    'clairvoyant',
    'clapping',
    'classic',
    'classy',
    'claustrophobic',
    'clawed',
    'clean',
    'clear-cut',
    'clever',
    'clingy',
    'clinical',
    'clogged',
    'cloistered',
    'close-knit',
    'closest',
    'clothed',
    'cloudless',
    'cloudy',
    'clueless',
    'clumsy',
    'clunky',
    'cluttered',
    'coarse',
    'coastal',
    'coaxial',
    'coexisting',
    'cognitive',
    'coherent',
    'cohesive',
    'coincidental',
    'cold-blooded',
    'cold-hearted',
    'collaborative',
    'collapsed',
    'collared',
    'collateral',
    'collectible',
    'collegial',
    'colloidal',
    'colloquial',
    'colonial',
    'colored',
    'colorful',
    'colorless',
    'colossal',
    'combatant',
    'combative',
    'combustible',
    'comely',
    'comfortable',
    'comical',
    'commanding',
    'commercial',
    'committed',
    'common',
    'communal',
    'communicative',
    'compact',
    'companionable',
    'comparative',
    'compassionate',
    'compatible',
    'compelling',
    'compendious',
    'competent',
    'competitive',
    'complaining',
    'complaisant',
    'complementary',
    'complete',
    'complex',
    'complicated',
    'composed',
    'composite',
    'compound',
    'comprehensive',
    'compressible',
    'compulsory',
    'computerized',
    'concave',
    'concealable',
    'concealing',
    'conceited',
    'concentric',
    'conceptual',
    'concerned',
    'conciliatory',
    'conclusive',
    'concrete',
    'concurrent',
    'condemned',
    'condensed',
    'condescending',
    'conditional',
    'conductive',
    'confident',
    'confidential',
    'confined',
    'confirmed',
    'confiscated',
    'conflicted',
    'confluent',
    'conformist',
    'confounded',
    'confused',
    'congressional',
    'conic',
    'conjugated',
    'connectable',
    'conniving',
    'conscientious',
    'conscious',
    'conscripted',
    'consecutive',
    'consenting',
    'conservative',
    'considerable',
    'considerate',
    'consistent',
    'conspiratorial',
    'constant',
    'constrictor',
    'consultive',
    'consumable',
    'consummate',
    'contagious',
    'containable',
    'contaminated',
    'contemplative',
    'contemptible',
    'contraband',
    'contradictory',
    'conventional',
    'convincing',
    'convoluted',
    'cooing',
    'cooked',
    'coolest',
    'cooperative',
    'coordinated',
    'copernican',
    'copy of',
    'coquettish',
    'coral',
    'corded',
    'cordial',
    'cordless',
    'corked',
    'cornered',
    'corny',
    'coronated',
    'corporal',
    'corporate',
    'correctable',
    'correlated',
    'corrupt',
    'corsair',
    'cosher',
    'cosmic',
    'cosmogenic',
    'cosmopolitan',
    'costly',
    'cotton',
    'coughing',
    'countable',
    'countywide',
    'courageous',
    'courteous',
    'covetous',
    'cowardly',
    'cowering',
    'cozy',
    'crabby',
    'cracked',
    'crackling',
    'crafty',
    'craggy',
    'cramped',
    'crashing',
    'crawling',
    'crazy',
    'creaking',
    'creative',
    'credible',
    'creeping',
    'creepy',
    'criminal',
    'crimson',
    'crispy',
    'crisscross',
    'critical',
    'crooked',
    'cross-eyed',
    'crowded',
    'crowdfunded',
    'crowned',
    'crucial',
    'crude',
    'cruel',
    'crumbling',
    'crunchy',
    'crushing',
    'crusty',
    'crying',
    'cryogenic',
    'cryptic',
    'crypto',
    'crystallized',
    'cubic',
    'cubist',
    'cuddly',
    'cultivated',
    'cultural',
    'cultured',
    'cumbersome',
    'cumulative',
    'cunning',
    'curdled',
    'curious',
    'curly',
    'curmudgeonly',
    'current',
    'cursed',
    'curt',
    'curvaceous',
    'curvy',
    'custom',
    'cute',
    'cutting-edge',
    'cyan',
    'cyclopean',
    'cylindric',
    'cynical',
    'daffy',
    'daft',
    'daily',
    'dainty',
    'damaging',
    'damp',
    'dancing',
    'dandy',
    'dangerous',
    'dank',
    'dapper',
    'daredevil',
    'daring',
    'dark wing',
    'darkened',
    'dashing',
    'dastardly',
    'dated',
    'dauntless',
    'dawdling',
    'daylong',
    'dazed',
    'dazzling',
    'deadly',
    'deadpan',
    'deafening',
    'dear',
    'deathless',
    'debatable',
    'debonair',
    'debunked',
    'decadent',
    'decaying',
    'deceivable',
    'decent',
    'decentralized',
    'deceptive',
    'decimal',
    'decisive',
    'declining',
    'decontaminated',
    'decorative',
    'decorous',
    'decreasing',
    'dedicated',
    'deducible',
    'deep fake',
    'deep space',
    'defendable',
    'defensible',
    'defiant',
    'definitely not',
    'definitive',
    'defoliated',
    'deformed',
    'deft',
    'defunct',
    'degraded',
    'dehydrated',
    'deific',
    'dejected',
    'delapidated',
    'delayed',
    'delectable',
    'deleterious',
    'deliberate',
    'delicate',
    'delicious',
    'delightful',
    'delinquent',
    'delirious',
    'delusive',
    'deluxe',
    'demagogic',
    'demanding',
    'demi',
    'democratic',
    'demoralizing',
    'demure',
    'deniable',
    'dense',
    'dental',
    'dependable',
    'deplorable',
    'deprecated',
    'depressive',
    'deprived',
    'depurated',
    'derailed',
    'deranged',
    'derelict',
    'derpy',
    'descending',
    'descriptive',
    'deserted',
    'deserving',
    'desiccated',
    'designer',
    'desirable',
    'desolate',
    'despairing',
    'desperate',
    'despicable',
    'despised',
    'despondent',
    'despotic',
    'destined',
    'destructive',
    'desultory',
    'detachable',
    'detailed',
    'detectable',
    'detective',
    'detergent',
    'determinative',
    'determined ',
    'deterministic',
    'detestable',
    'detrimental',
    'deus ex',
    'devalued',
    'devastating',
    'developed',
    'devious',
    'devoid',
    'devoted',
    'devout',
    'diacritical',
    'diagonal',
    'dialectical',
    'diamagnetic',
    'diastolic',
    'diatonic',
    'dichotomous',
    'didactic',
    'dietary',
    'different',
    'differentiated',
    'difficult',
    'diffused',
    'digestive',
    'digital',
    'digitigrade',
    'dignified',
    'dilapidated',
    'dilatory',
    'dilettante',
    'diligent',
    'dilute',
    'diminishing',
    'diminutive',
    'dimmed',
    'dingy',
    'dinky',
    'diploid',
    'diplomatic',
    'dire',
    'directionless',
    'dirtiest',
    'disaffected',
    'disagreeable',
    'disappearing',
    'disappointing',
    'disapproving',
    'disarming',
    'disarranged',
    'disarrayed',
    'disastrous',
    'discarded',
    'discerned',
    'disciform',
    'disciplined',
    'disclosed',
    'discomfiting',
    'disconcerting',
    'disconnected',
    'disconsolate',
    'discontent',
    'discordant',
    'discouraging',
    'discovered',
    'discredited',
    'discreet',
    'discriminated',
    'discursive',
    'discussable',
    'disdainful',
    'disembodied',
    'disenchanted',
    'disgraceful',
    'disguised',
    'disgusted',
    'dishonest',
    'dishonored',
    'dishy',
    'disillusioned',
    'disinfectant',
    'disingenuous',
    'disjoined',
    'disjunct',
    'dismayed',
    'disordered',
    'disorganised',
    'disorganized',
    'dispersed',
    'displaced',
    'displeased',
    'disposable',
    'disproportional',
    'disputable',
    'disqualified',
    'disrespectful',
    'disruptive',
    'dissatisfied',
    'dissoluble',
    'dissonant',
    'dissuasive',
    'distant',
    'distasteful',
    'distilled',
    'distinctive',
    'distinguished',
    'distorted',
    'distracting',
    'distressed',
    'distributive',
    'disturbing',
    'divergent',
    'diversified',
    'diverted',
    'divided',
    'divine',
    'dizzy',
    'docile',
    'doctor',
    'doctoral',
    'documentary',
    'dodgy',
    'dogmatic',
    'doleful',
    'dollish',
    'doltish',
    'domestic',
    'dominant',
    'doodling',
    'doom',
    'doomsday',
    'dope',
    'dormant',
    'dotted',
    'double-edged',
    'doubtful',
    'dovish',
    'dowdy',
    'downcast',
    'downhill',
    'downloadable',
    'downstream',
    'downtown',
    'dragonborn',
    'drained',
    'dramatic',
    'drastic',
    'drawn',
    'dreadful',
    'dreamy',
    'drear',
    'dressy',
    'dried',
    'drinkable',
    'driving',
    'drizzly',
    'droopy',
    'drowsy',
    'drunk',
    'dry',
    'dual-wielding',
    'dubious',
    'duct-taped',
    'ductile',
    'dull',
    'dummy',
    'duplex',
    'duplicate',
    'duplicitous',
    'durable',
    'duralloy',
    'dusky',
    'dusty',
    'dutiful',
    'dwarf',
    'dwindling',
    'dynamic ',
    'dynastic',
    'dyspeptic',
    'dystopian',
    'eager',
    'eagle-eyed',
    'eared',
    'earl grey ',
    'earless',
    'earliest',
    'earnest',
    'earsplitting',
    'earth-shattering',
    'earthbound',
    'eastmost',
    'easy-going',
    'ebony',
    'ebullient',
    'eccentric',
    'echoing',
    'eclectic',
    'ecological',
    'economical',
    'ecstatic',
    'ectodermic',
    'ectothermic',
    'ecumenic',
    'edgeless',
    'edgy',
    'edible',
    'editable',
    'educational',
    'eellike',
    'eerie',
    'effaceable',
    'effective',
    'effervescent',
    'efficacious',
    'efficient',
    'effortless',
    'egalitarian',
    'egg-shaped',
    'egocentric',
    'egomaniacal',
    'egotistic',
    'egregious',
    'elaborate',
    'elastic',
    'elated',
    'elder',
    'eldritch',
    'elect',
    'electrified',
    'electronic',
    'elegant ',
    'elemental',
    'elementary',
    'elephantine',
    'elevated',
    'elfish',
    'eligible',
    'elite',
    'elliptic',
    'elongated',
    'eloquent',
    'elusive',
    'emaciated',
    'emancipative',
    'embarrassing',
    'embedded',
    'embittered',
    'emblematic',
    'embodied',
    'emboldened',
    'embossed',
    'embroiled',
    'emergency',
    'emergent',
    'emeritus',
    'eminent',
    'emotional',
    'empathetic',
    'emperor',
    'emphasized',
    'empiric',
    'empirical',
    'employable',
    'empty-handed',
    'enabled',
    'enamored',
    'enchanted',
    'encircled',
    'enclosed',
    'encoded',
    'encouraging',
    'encrusted',
    'encrypted',
    'endangered',
    'endearing',
    'endemic',
    'endless',
    'endogenous',
    'endothermic',
    'enduring',
    'energizing',
    'enervating',
    'enforceable',
    'engaging',
    'english-speaking',
    'engorged',
    'engraved',
    'engrossing',
    'enhanced',
    'enigmatic',
    'enjoyable',
    'enlarged',
    'enlightened',
    'enormous',
    'enraged',
    'enterprising',
    'entertaining',
    'enthralling',
    'enthusiastic',
    'enticing',
    'entrancing',
    'entrenched',
    'entropic',
    'enumerable',
    'envious',
    'environmental',
    'eparchial',
    'ephemeral',
    'epic',
    'epidemic',
    'epidermic',
    'episodic',
    'eponymous',
    'equanimous',
    'equatorial',
    'equidistant',
    'equippable',
    'equiprobable',
    'equivalent',
    'equivocal',
    'eradicable',
    'erasable',
    'ergonomic',
    'erosive',
    'erratic',
    'error-prone',
    'erudite',
    'eruptive',
    'escalating',
    'escaped',
    'esoteric',
    'essence of',
    'essential',
    'established',
    'estimated',
    'estranged',
    'eternal',
    'eternal mystery',
    'ethereal',
    'ethical',
    'euclidean',
    'euphoric',
    'evaluative',
    'evaporable',
    'evasive',
    'even-tempered',
    'eventful',
    'eventual',
    'ever-changing',
    'ever-present',
    'evergreen',
    'everlasting',
    'everyday',
    'everything except',
    'evident',
    'evil',
    'exactly',
    'exaggerated',
    'exalted',
    'exasperating',
    'excellent',
    'exceptional',
    'excessive',
    'exchangeable',
    'exciting',
    'exclamatory',
    'exclusive',
    'executable',
    'executive',
    'exempt',
    'exhausted',
    'exhilarated',
    'existential',
    'exogenous',
    'exothermic',
    'exotic',
    'expansible',
    'expectable',
    'expendable',
    'expensive',
    'experienced',
    'experimental',
    'expert',
    'expired',
    'explicit',
    'exploding',
    'exploitative',
    'explorer',
    'explosive',
    'exponential',
    'exposed',
    'express',
    'expressive',
    'exquisite',
    'extendable',
    'extensive',
    'exterior',
    'external',
    'exterritorial',
    'extinct',
    'extinguishable',
    'extra-large',
    'extra-size',
    'extractible',
    'extraordinary',
    'extrapolated',
    'extraterrestrial',
    'extravagant',
    'extravehicular',
    'extreme',
    'extremist',
    'extrinsic',
    'extroverted',
    'extrusive',
    'eye-catching',
    'eyeless',
    'fabled',
    'fabricated',
    'fabulous',
    'faceless',
    'facile',
    'fading',
    'failing as',
    'faint',
    'fair',
    'fairy',
    'faithful',
    'faithless',
    'fake',
    'falling',
    'false',
    'falsified',
    'familiar',
    'famished',
    'famous',
    'fanatic',
    'fancy',
    'fanged',
    'fantastic',
    'far-flung',
    'farm',
    'farming',
    'farsighted',
    'fascinating',
    'fashionable',
    'fast-paced',
    'faster than',
    'fat',
    'fatal',
    'fateful',
    'fathomable',
    'fatigued',
    'faultless',
    'faulty',
    'faux',
    'favorable ',
    'fearful',
    'fearless ',
    'fearsome',
    'feasible',
    'feathered',
    'featured',
    'featureless',
    'federal',
    'feeble',
    'feigned',
    'fellow',
    'felonious',
    'fennec',
    'feral',
    'fermented',
    'ferocious',
    'fervent',
    'festive',
    'feudal',
    'fiberoptic',
    'fickle',
    'fictional',
    'field',
    'fiendish',
    'fierce',
    'fiery',
    'fighter',
    'filtered',
    'filthy',
    'final',
    'finally a proper',
    'financial',
    'fine',
    'finished',
    'finite',
    'firebreathing',
    'fireproof',
    'first',
    'first aid',
    'first year',
    'first-class',
    'fiscal',
    'fisheye',
    'fissile',
    'fixed',
    'fizzy',
    'flamboyant',
    'flameproof',
    'flaming',
    'flammable',
    'flashy',
    'flattened',
    'flattering',
    'flavorless',
    'flawless',
    'fleeting',
    'flexible',
    'flickering',
    'flightless',
    'flinty',
    'flipped',
    'flirtatious',
    'floating',
    'flooded',
    'floppy',
    'floral',
    'flourishing',
    'flowering',
    'flowerless',
    'fluent',
    'fluffy',
    'fluid',
    'flushed',
    'fluttering',
    'flying',
    'focused',
    'foggy',
    'foil-hatted',
    'foldable',
    'foodless',
    'foolproof',
    'footless',
    'footsore',
    'forbearing',
    'forbidden',
    'force-sensitive',
    'forceful',
    'foregoing',
    'foreign',
    'foremost',
    'forensic',
    'foreseeable',
    'forfeit',
    'forged',
    'forgetful',
    'forgivable',
    'forgotten',
    'forked',
    'formal',
    'former',
    'formidable',
    'formless',
    'forthcoming',
    'forthright',
    'fortified',
    'fortissimo',
    'fortuitous ',
    'fortunate',
    'fossilized',
    'foul',
    'fragile',
    'fragmented',
    'fragrant',
    'frail',
    'frank',
    'frantic',
    'fraudulent',
    'frayed',
    'freaky',
    'freckled',
    'free',
    'freeborn',
    'freelance',
    'freewill',
    'freezing',
    'french-speaking',
    'frenzied',
    'frequent',
    'fresh',
    'frictionless',
    'fried',
    'friendly',
    'frightening',
    'frigid',
    'frilled',
    'frivolous',
    'frontmost',
    'frowning',
    'frozen',
    'fruitful',
    'frustrated',
    'fueled',
    'fugitive',
    'full metal',
    'full-blown',
    'full-scale',
    'full-time',
    'fully-featured',
    'functional',
    'fundamental',
    'fungal',
    'fungible',
    'funky',
    'funny',
    'furious',
    'furnished',
    'furry',
    'fusion',
    'futile',
    'future-telling',
    'futuristic',
    'fuzzy',
    'gaelic',
    'gainful',
    'galactic',
    'galapagos',
    'gallant',
    'galling',
    'galvanising',
    'gambler',
    'game-changing',
    'gamer',
    'gargantuan',
    'garlicky',
    'garmented',
    'garnished',
    'garrulous',
    'gaseous',
    'gastronomic',
    'gathered',
    'gatling',
    'gauche',
    'gaudy',
    'gaunt',
    'gaussian',
    'gauzy',
    'gawky',
    'geared up',
    'geeky',
    'gelatinous',
    'gemstone',
    'general-purpose',
    'generalized',
    'generative',
    'generic',
    'generous',
    'genetic',
    'genial',
    'genius',
    'genteel',
    'gentle',
    'genuine',
    'geocentric',
    'geodesic',
    'geographic',
    'geologic',
    'geometric',
    'geophysical',
    'geopolitical',
    'geostationary',
    'geothermal',
    'geriatric',
    'ghastly',
    'ghostly',
    'ghoulish',
    'giant',
    'giddy',
    'gifted',
    'gigantic',
    'giggling',
    'gilded',
    'ginger',
    'glacial',
    'glamorous',
    'glandular',
    'glaring',
    'glassed',
    'gleaming ',
    'gleeful',
    'gliding',
    'glimmering ',
    'glistening',
    'glitchy',
    'glittering',
    'glitzy',
    'global',
    'globular',
    'gloomy',
    'glorious',
    'glossy',
    'glowing ',
    'glum',
    'gluttonous',
    'gnarled',
    'gnostic',
    'gobsmacked',
    'godly',
    'goggle-eyed',
    'gold-digging',
    'golden',
    'good-looking',
    'good-tempered',
    'goodhearted',
    'goofy',
    'gordian',
    'gorgeous',
    'gossipy',
    'gothic',
    'governmental',
    'graceful',
    'graceless',
    'gracious',
    'gradual',
    'graduated',
    'grainy',
    'grammatical',
    'grand',
    'grandiloquent',
    'grandiose',
    'granular',
    'graphical',
    'grasping',
    'grateful',
    'gratified',
    'gratuitous',
    'grave',
    'gray',
    'gray-haired',
    'grayscale',
    'greasy',
    'greater',
    'greedy',
    'greenhouse',
    'gregarious',
    'grieving',
    'grievous',
    'grilled',
    'grim',
    'grimacing',
    'grindy',
    'grinning',
    'gripping ',
    'gritty',
    'grizzly',
    'groomed',
    'groovy',
    'gross',
    'grotesque',
    'ground-floor',
    'groundbreaking',
    'grounded',
    'growing',
    'grown-up',
    'grueling',
    'gruesome',
    'gruff',
    'grumpy',
    'guaranteed',
    'guardian',
    'guided',
    'guileless',
    'guilty',
    'gullible',
    'gummy',
    'gutsy',
    'guttural',
    'hacked',
    'hackneyed',
    'haggard',
    'hair-raising',
    'hairless',
    'hairy',
    'halcyon',
    'hale',
    'halfhearted',
    'hallowed',
    'hallucinogenic',
    'halting',
    'hand-washed',
    'handheld',
    'handicapped',
    'handmade',
    'hands-off',
    'hands-on',
    'handsome',
    'handwoven',
    'handy',
    'hangdog',
    'hanging',
    'haphazard',
    'hapless',
    'happiest',
    'haptic',
    'hard-headed',
    'hard-shelled',
    'hard-to-find',
    'hard-working',
    'hardback',
    'hardcoded',
    'hardcore',
    'hardened',
    'hardhearted',
    'hardy',
    'harebrained',
    'harmful',
    'harmless',
    'harmonious',
    'harried',
    'harsh',
    'hashtagged',
    'hasty',
    'hateful',
    'hatted',
    'haughty',
    'haunting',
    'hawk-eyed',
    'hazardous',
    'headless',
    'healing',
    'healthy',
    'heartbreaking',
    'heartening',
    'heartless',
    'heartsick',
    'heartwarming ',
    'hearty',
    'heated',
    'heavenly',
    'heavy-armed',
    'heavyhearted',
    'hectic',
    'hegemonic',
    'heinous',
    'heliocentric',
    'helmeted',
    'helpful',
    'helpless',
    'hematogenic',
    'hemispheric',
    'hemophilic',
    'heraldic',
    'herbal',
    'herbivorous',
    'heretical',
    'hermetic',
    'hermit',
    'heroic',
    'hesitant',
    'heterogeneous',
    'heuristic',
    'hexadecimal',
    'hexagonal',
    'hexed',
    'hi-tech',
    'hibernating',
    'hidden',
    'hideous',
    'hierarchic',
    'hieroglyphic',
    'high',
    'high-octane',
    'high-order',
    'high-pitched',
    'high-quality',
    'high-ranked',
    'high-risk',
    'high-tech',
    'highborn',
    'highland',
    'hilarious',
    'hindering',
    'hip',
    'hircine',
    'hired',
    'hissing',
    'historical',
    'ho-hum',
    'hoarse',
    'hoity-toity',
    'hokey',
    'holiday',
    'holistic',
    'hollow',
    'holographic',
    'holy',
    'homegrown',
    'homeless',
    'homely',
    'homemade',
    'homesick',
    'homey',
    'homicidal',
    'homing',
    'homogeneous',
    'honest',
    'honey',
    'honking',
    'honorable',
    'hoofed',
    'hooked',
    'hooved',
    'hopeful',
    'hopeless',
    'horizontal',
    'horned',
    'horrendous',
    'horrible',
    'horrid',
    'horrifying',
    'hospitable',
    'hostile',
    'hot-blooded',
    'hot-linked',
    'hot-tempered',
    'hotheaded',
    'hourly',
    'howling',
    'hubristic',
    'huffy',
    'huge',
    'huggable',
    'hulking',
    'human-like',
    'humanistic',
    'humanitarian',
    'humble',
    'humid',
    'humiliating',
    'humming',
    'humongous',
    'humorless',
    'humorous',
    'humourless',
    'humpbacked',
    'hungry',
    'hunky',
    'hurried',
    'hurtful',
    'hushed',
    'husky',
    'hybrid',
    'hydraulic',
    'hydrophobic',
    'hydroponic',
    'hydrostatic',
    'hygienic',
    'hyped',
    'hyperactive',
    'hyperbolic',
    'hypercasual',
    'hypercritical',
    'hypernatural',
    'hypersensitive',
    'hypersonic',
    'hypertonic',
    'hypnotic',
    'hypothetical',
    'hysterical',
    'icky',
    'iconic',
    'iconoclastic',
    'icosahedral',
    'icy',
    'ideal',
    'idealistic',
    'idealized',
    'identical',
    'identifiable',
    'ideological',
    'idiomatic',
    'idiopathic',
    'idiosyncratic',
    'idle',
    'idolized',
    'idyllic',
    'iffy',
    'igneous',
    'ignitable',
    'ignoble',
    'ignorable',
    'ignorant',
    'ill-fated',
    'illaudable',
    'illegal',
    'illegitimate',
    'illicit',
    'illiterate',
    'illogical',
    'illuminating',
    'illusory',
    'illustrated',
    'illustrious',
    'imaginary',
    'imaginative',
    'imbalanced',
    'imitative',
    'immaculate',
    'immaterial',
    'immature',
    'immeasurable',
    'immediate',
    'immense',
    'imminent',
    'immobile',
    'immodest',
    'immoral',
    'immovable',
    'immunized',
    'immunodeficient',
    'immutable',
    'impactful',
    'impaired',
    'impalpable',
    'impartial',
    'impassable',
    'impatient',
    'impeccable',
    'impecunious',
    'impending',
    'impenetrable',
    'imperative',
    'imperfect',
    'imperial',
    'impermeable',
    'impersonating',
    'impertinent',
    'impervious',
    'impetuous',
    'impish',
    'implausible',
    'implicated',
    'implicit',
    'implosive',
    'impolite',
    'important',
    'imported',
    'impossible',
    'impostor',
    'impractical',
    'imprecise',
    'impressionist',
    'impressive',
    'improbable',
    'impromptu',
    'improper',
    'improving',
    'improvised',
    'imprudent',
    'impudent',
    'impugnable',
    'impulsive',
    'impure',
    'inaccessible',
    'inaccurate',
    'inactive',
    'inadequate',
    'inadmissible',
    'inadvertent',
    'inadvisable',
    'inalienable',
    'inalterable',
    'inanimate',
    'inapplicable',
    'inappropriate',
    'inapt',
    'inattentive',
    'inaudible',
    'inauspicious',
    'inauthentic',
    'inbound',
    'inbuilt',
    'incalculable',
    'incandescent',
    'incapable',
    'incarnate',
    'incendiary',
    'inceptive',
    'incidental',
    'inclined',
    'inclusive',
    'incognito',
    'incoherent',
    'incombustible',
    'incoming',
    'incomparable',
    'incompatible',
    'incompetent',
    'incomplete',
    'incomprehensible',
    'incomputable',
    'inconceivable',
    'inconclusive',
    'inconsequential',
    'inconsiderate',
    'inconsistent',
    'inconspicuous',
    'inconstant',
    'inconvenient',
    'incorporated',
    'incorrect',
    'incorrigible',
    'incorruptible',
    'increasing',
    'incredible ',
    'incremental',
    'incumbent',
    'incurable',
    'indebted',
    'indecent',
    'indecipherable',
    'indecisive',
    'indefatigable',
    'indefinite',
    'independent',
    'indescribable',
    'indestructible',
    'indeterminate',
    'indexed',
    'indicative',
    'indie',
    'indifferent',
    'indigenous',
    'indigestible',
    'indigo',
    'indirect',
    'indiscreet',
    'indiscriminate',
    'indispensable',
    'indisputable',
    'individualistic',
    'indivisible',
    'indoctrinated',
    'indoor',
    'inductive',
    'industrial',
    'industrious',
    'indwelling',
    'inedible',
    'ineffable',
    'ineffective',
    'inelastic',
    'inept',
    'inert',
    'inescapable',
    'inevitable',
    'inexcusable',
    'inexpensive',
    'inexperienced',
    'inexplicable',
    'infallible',
    'infamous',
    'infectious',
    'infelicitous',
    'inferior',
    'infernal',
    'infinite',
    'inflammable',
    'inflatable',
    'inflexible',
    'influential',
    'informal',
    'informative',
    'infrared',
    'infrasonic',
    'infrequent',
    'infuriating',
    'ingenious',
    'inglorious',
    'inhabitable',
    'inharmonic',
    'inherent',
    'inherited',
    'inhibited',
    'inhospitable',
    'inhuman',
    'initial',
    'injurious',
    'inky',
    'inland',
    'inmost',
    'innate',
    'inner',
    'innocent',
    'innovative',
    'innoxious',
    'innuendo',
    'innumerable',
    'inoffensive',
    'inoperative',
    'inorganic',
    'inquisitive',
    'insecure',
    'insensitive',
    'inseparable',
    'insightful',
    'insignificant',
    'insincere',
    'insipid',
    'insolent',
    'insoluble',
    'insolvent',
    'insomniac',
    'inspirational',
    'instant',
    'instinctive',
    'institutional',
    'instrumental',
    'insubstantial',
    'insufferable',
    'insufficient',
    'insulting',
    'insurmountable',
    'insusceptible',
    'intact',
    'integral',
    'integrated',
    'intellectual',
    'intelligent',
    'intelligible',
    'intended',
    'intense',
    'intensive',
    'intentional',
    'interactive',
    'interchangeable',
    'interdepartmental',
    'interdisciplinary',
    'interesting',
    'intergalactic',
    'interior',
    'intermediate',
    'internal',
    'internal combustion',
    'international',
    'interpolated',
    'interpretative',
    'interrogative',
    'interstellar',
    'intimidating',
    'intoxicating',
    'intransigent',
    'intrepid',
    'intricate',
    'intriguing',
    'intrinsic',
    'introductory',
    'introverted',
    'intrusive',
    'intuitive',
    'invalid',
    'invaluable',
    'invariant',
    'invasive',
    'inventive',
    'inverse',
    'invertebrate',
    'inverted',
    'invigorating',
    'invincible',
    'invisible',
    'invisible pink',
    'invitational',
    'inviting',
    'involuntary',
    'involved',
    'invulnerable',
    'ionized',
    'irascible',
    'irate',
    'iridescent',
    'iron',
    'ironclad',
    'ironed',
    'ironic',
    'irrational',
    'irreclaimable',
    'irreconcilable',
    'irrefutable',
    'irregular',
    'irrelevant',
    'irresistible',
    'irreversible',
    'irrevocable',
    'irritable',
    'isolated',
    'isomeric',
    'isomorphic',
    'isothermic',
    'isotopic',
    'isotropic',
    'italic',
    'itchy',
    'iterative',
    'itinerant',
    'itty-bitty',
    'jack the',
    'jacobean',
    'jade',
    'jaded ',
    'jagged ',
    'jaggy ',
    'jammed ',
    'jangling ',
    'jarring ',
    'jaunty ',
    'jaw-dropping',
    'jazzy ',
    'jealous ',
    'jedi',
    'jeering ',
    'jelly',
    'jesting ',
    'jet',
    'jeweled ',
    'jiggish ',
    'jingly ',
    'jinxed ',
    'jittery ',
    'jobless ',
    'jocose ',
    'jocular ',
    'jocund ',
    'joint',
    'joking ',
    'jolly ',
    'jovial ',
    'joyful ',
    'joyless',
    'jubilant ',
    'judgemental ',
    'judicious ',
    'juiceless ',
    'jumbo ',
    'jumpy ',
    'jungly ',
    'junior ',
    'jurassic ',
    'jurisdictional',
    'juristic ',
    'just ',
    'just another',
    'justifiable ',
    'juvenile ',
    'kabbalistic ',
    'kaleidoscopic ',
    'kawai',
    'keen ',
    'kempt ',
    'keyless ',
    'killer ',
    'kind-hearted',
    'kindred ',
    'kinetic ',
    'king-sized',
    'kingly ',
    'kitchen',
    'kleptomanic',
    'klutzy ',
    'knackered ',
    'knavish ',
    'knightly ',
    'knitted ',
    'komodo',
    'kooky ',
    'kosher ',
    'labeled',
    'laborsaving',
    'lackadaisical ',
    'lackluster ',
    'laid-off',
    'lame ',
    'lamentable ',
    'laminal',
    'laminar',
    'languid ',
    'lanky ',
    'large-scale',
    'last-minute',
    'late ',
    'latent ',
    'lateral',
    'latin',
    'laudable ',
    'laughable',
    'laureate',
    'laureled ',
    'lavender ',
    'lavish ',
    'law-abiding',
    'lawful ',
    'lawful evil',
    'lawful good',
    'lawful neutral',
    'lawless ',
    'lax ',
    'lazy ',
    'leading',
    'leafless ',
    'leafy ',
    'leakproof',
    'learnable',
    'leather',
    'leathery ',
    'left-chiral',
    'left-handed',
    'leftover ',
    'legalized',
    'legendary',
    'legible ',
    'legitimate ',
    'leisure suit',
    'lemon',
    'lengthy ',
    'lethal ',
    'lethargic',
    'lexical',
    'liable ',
    'liberal',
    'licensed',
    'life-giving',
    'life-threatening',
    'lifeless',
    'lifelong ',
    'light-armed',
    'light-footed',
    'light-headed',
    'light-hearted',
    'light-minded',
    'lightweight',
    'likable ',
    'like-minded',
    'lilliputian',
    'limber ',
    'limited',
    'limitless',
    'limping',
    'linear',
    'lingering',
    'linguistic',
    'lionhearted',
    'liquid',
    'literally',
    'literate ',
    'lithographic',
    'little',
    'lively',
    'loaded ',
    'loathsome',
    'localized',
    'locked on',
    'locomotive',
    'lofty',
    'logarithmic',
    'logical ',
    'logistical',
    'lone',
    'lonely',
    'long-eared',
    'long-lived',
    'long-range',
    'long-term',
    'longitudinal',
    'looks like',
    'loony',
    'loopy ',
    'loose',
    'loquacious ',
    'lordly',
    'lorem ipsum',
    'lossless',
    'lossy',
    'lost',
    'loud',
    'lousy',
    'loutish ',
    'lovable',
    'love and',
    'loveless',
    'lovely ',
    'lovesick',
    'loving ',
    'low-budget',
    'low-density',
    'low-fat',
    'low-grade',
    'low-latency',
    'low-level',
    'low-maintenance',
    'low-orbit',
    'low-pressure',
    'low-priced',
    'low-ranking',
    'low-risk',
    'lowland',
    'lowly ',
    'loyal ',
    'lucid ',
    'lucky ',
    'lugubrious ',
    'lukewarm',
    'luminescent',
    'luminous',
    'lunar',
    'lunatic',
    'luscious',
    'lush',
    'lustrous ',
    'luxurious',
    'lying',
    'macabre ',
    'machiavellian ',
    'macrobiotic',
    'macroscopic ',
    'mad',
    'maddening',
    'magic',
    'magical',
    'magistrate',
    'magnanimous ',
    'magnetic ',
    'magnificent ',
    'main ',
    'mainstream',
    'majestic ',
    'major',
    'makeshift',
    'malformed',
    'malicious',
    'malign',
    'malleable ',
    'malnourished',
    'man-made',
    'manageable',
    'mandatory',
    'maned',
    'maneuverable',
    'maniacal ',
    'manicured ',
    'manifested',
    'manifold',
    'manipulative',
    'mannered',
    'mantled',
    'marauding',
    'marble',
    'marginal',
    'marine',
    'maritime',
    'marked',
    'marketable ',
    'maroon',
    'marriageable',
    'martial',
    'martian',
    'marvelous ',
    'masked',
    'masochistic',
    'mass-produced',
    'massive',
    'master',
    'masterful ',
    'matchless',
    'material',
    'mathematical',
    'mature ',
    'maverick',
    'maximal',
    'meager',
    'mean ',
    'meandering',
    'meaningful',
    'meaningless',
    'measureless',
    'mechanized',
    'meddling',
    'medical',
    'medieval',
    'mediocre',
    'meditative',
    'mediterranean',
    'medium-size',
    'meek ',
    'mega',
    'megalithic',
    'melancholic',
    'mellow',
    'melodic',
    'melodramatic ',
    'melting',
    'meme-worthy',
    'memorable ',
    'menacing',
    'mental',
    'mercantile',
    'mercenary',
    'merchantable',
    'merciful',
    'merciless',
    'mercurial ',
    'mere',
    'meretricious ',
    'merited',
    'meritless',
    'meritous',
    'merry',
    'mesmerizing',
    'messy',
    'metabolic',
    'metallic ',
    'metallurgical',
    'metamorphous',
    'metaphorical',
    'metaphysical',
    'metastable',
    'methodical',
    'meticulous ',
    'metric',
    'metrological',
    'metropolitan',
    'miasmic',
    'micro',
    'microbial',
    'microscopic',
    'microwaveable',
    'middle',
    'midget',
    'midway',
    'midweek',
    'mighty',
    'migratory',
    'mild ',
    'militant ',
    'militaristic',
    'military',
    'millenium',
    'millennial',
    'mimic',
    'mind-bending',
    'mind-blowing',
    'mind-boggling',
    'mindful ',
    'mindless',
    'mineral',
    'minesweeper',
    'miniature',
    'minimalist',
    'mining',
    'minor',
    'minty',
    'minuscule',
    'minute',
    'miraculous',
    'mirky',
    'mirrored',
    'mirthful ',
    'misanthropic ',
    'misbranded',
    'miscellaneous',
    'mischievous',
    'miserable ',
    'miserly ',
    'misfortunate',
    'misguided',
    'mislabeled',
    'misleading ',
    'mismatched',
    'misplaced',
    'missing',
    'mistakable',
    'mistrusting',
    'misty',
    'misunderstood',
    'mithril',
    'mixed',
    'mnemonic',
    'mobile',
    'mocking',
    'modal',
    'modded',
    'model',
    'moderate',
    'modern ',
    'modest ',
    'modifiable',
    'modish ',
    'modular',
    'modulated',
    'molded',
    'molecular',
    'molten',
    'monarchic',
    'monday',
    'monetary',
    'moneymaking',
    'monoatomic',
    'monochrome',
    'monocled',
    'monolingual',
    'monolithic',
    'monomorphic ',
    'mononuclear',
    'monophonic',
    'monosyllabic',
    'monotonous',
    'monstrous',
    'monthly',
    'monumental',
    'moody ',
    'moon',
    'moonstruck',
    'moral ',
    'morbid',
    'morse-encoded',
    'mortal',
    'mosaic',
    'mossy',
    'mothproof',
    'motionless',
    'motivated',
    'motivational',
    'motiveless',
    'motorized',
    'mountain',
    'mounted',
    'mourning',
    'mouthless',
    'moving ',
    'mucky',
    'muddy',
    'muffled',
    'mulish ',
    'multicellular',
    'multicolored',
    'multicultural',
    'multidimensional',
    'multilingual',
    'multinational',
    'multiplayer',
    'multiplex',
    'multipurpose ',
    'multiverse',
    'mundane ',
    'municipal',
    'munificent ',
    'murderous',
    'murky',
    'murmurous',
    'muscular',
    'musical',
    'mutagenic',
    'mutant',
    'muted',
    'mutinous ',
    'myopic ',
    'mysterious ',
    'mystified',
    'mythologic',
    'naive ',
    'nameless ',
    'narcissistic ',
    'narrow-minded',
    'nasty ',
    'national ',
    'native ',
    'natural ',
    'naughty ',
    'nautical',
    'naval',
    'navy-blue',
    'nearsighted ',
    'neat',
    'nebulous ',
    'necessary',
    'necromantic',
    'needless',
    'needy ',
    'nefarious ',
    'negative',
    'neglectful',
    'negligent ',
    'negotiable',
    'neighbor',
    'neo',
    'neoclassic',
    'nerdy ',
    'nerfed',
    'nervous ',
    'neural',
    'neutral evil',
    'neutral good',
    'never-ending',
    'newborn',
    'newsworthy',
    'nice ',
    'nifty',
    'nightly',
    'nightmarish',
    'nihilistic',
    'nimble',
    'ninja',
    'no-win',
    'noble ',
    'nocturnal ',
    'noire',
    'noisy ',
    'nomadic',
    'nominal ',
    'nominative',
    'non fungible',
    'non-aggressive',
    'non-responsive',
    'non-threatened',
    'non-transferable',
    'nonabsorptive',
    'nonadhesive',
    'nonchalant ',
    'noncombatant',
    'noncommercial',
    'noncompetitive',
    'nonconformist',
    'nondeductible',
    'nondestructive',
    'nonessential ',
    'nonexistent',
    'nonexplosive',
    'nonfatal',
    'nonflammable',
    'nonfunctional',
    'noninfectious',
    'noninterchangeable',
    'noninvasive',
    'nonlinear',
    'nonobligatory',
    'nonpartisan ',
    'nonprofit ',
    'nonpublic',
    'nonrefundable',
    'nonrenewable',
    'nonresistant',
    'nonretractable',
    'nonsensical ',
    'nonstop',
    'nonuniform',
    'nonverbal',
    'nordic',
    'normal ',
    'northbound',
    'northeastern',
    'northwestern',
    'nostalgic ',
    'nosy ',
    'not only',
    'notable ',
    'noteworthy ',
    'nothing but',
    'noticeable',
    'notorious ',
    'nourishing ',
    'novel ',
    'noxious ',
    'nuclear',
    'numb ',
    'numeric',
    'nutritious ',
    'oafish',
    'obedient',
    'obeisant',
    'objectionable',
    'obligatory',
    'obliging',
    'oblique',
    'obliterated',
    'oblivious',
    'obnoxious',
    'obscene',
    'obscure',
    'observant',
    'obsessed',
    'obsolete',
    'obstinate',
    'obstructive',
    'obvious',
    'occasional',
    'occupied',
    'oceanic',
    'octagonal',
    'odd',
    'odious',
    'offbeat',
    'offensive',
    'officer',
    'official',
    'officious',
    'offshore',
    'oily',
    'old-fashioned',
    'oligarchic',
    'olive',
    'olympic',
    'ominous',
    'omnidirectional',
    'omnipotent',
    'omnipresent',
    'omniscient',
    'omnivore',
    'one punch',
    'one-of-a-kind',
    'onetime',
    'ongoing',
    'online',
    'ontological',
    'oozy',
    'opalescent',
    'opaque',
    'open-minded',
    'opensource',
    'operative',
    'opinionated',
    'opportune',
    'opportunist',
    'opposing',
    'oppressive',
    'optical',
    'optimal',
    'optimistic',
    'optimus',
    'optional',
    'opulent',
    'orange',
    'orbital',
    'orchestral',
    'ordained',
    'orderly',
    'ordinary',
    'organic',
    'organized',
    'oriented',
    'origami',
    'original',
    'ornamental',
    'ornate',
    'ornery',
    'orotund',
    'orthodox',
    'orthogonal',
    'oscar-nominated',
    'ostentatious',
    'otherworldly',
    'outbound',
    'outcast',
    'outclassed',
    'outdated',
    'outdoor',
    'outgoing',
    'outlandish',
    'outlawed',
    'outrageous',
    'outsourced',
    'outspoken',
    'outstanding',
    'outwordly',
    'oval',
    'overabundant',
    'overachieving',
    'overactive',
    'overambitious',
    'overbearing',
    'overblown',
    'overbold',
    'overburdened',
    'overcast',
    'overconfident',
    'overcooked',
    'overdressed',
    'overdue',
    'overemotional',
    'overenthusiastic',
    'overexcited',
    'overextended',
    'overfed',
    'overgrown',
    'overhead',
    'overheated',
    'overindulgent',
    'overjoyed',
    'overloaded',
    'overnight',
    'overoptimistic',
    'overpowered',
    'overpriced',
    'overprotective',
    'overqualified',
    'overrated',
    'overripe',
    'oversea',
    'oversimplified',
    'oversize',
    'overweight',
    'overwhelming',
    'overworked',
    'overwrought',
    'overzealous',
    'own best',
    'oxidized',
    'pacific',
    'pacifist',
    'packed',
    'paid',
    'painful',
    'painless',
    'painstaking',
    'painted',
    'pale',
    'paleolithic',
    'pallid',
    'pampered',
    'pandemic',
    'panicky',
    'panoramic',
    'paper',
    'parabolic',
    'paradoxical',
    'parallel',
    'paramagnetic',
    'paramedical',
    'paranoid',
    'paranormal',
    'pardonable',
    'parking',
    'parliamentary',
    'parody of',
    'parsimonious',
    'part-time',
    'partial',
    'particular',
    'particulate',
    'partisan',
    'partying',
    'passing',
    'passionate',
    'passive',
    'past',
    'pastel',
    'pasteurized',
    'patented',
    'pathogenic',
    'pathological',
    'patient',
    'patriotic',
    'patronizing',
    'paying',
    'peaceful',
    'peacekeeping',
    'peckish',
    'pedagogical',
    'pedal',
    'pedantic',
    'pedestrian',
    'pediatric',
    'pedigree',
    'peer-reviewed',
    'peerless',
    'peevish',
    'pending',
    'penetrable',
    'penniless',
    'pentagonal',
    'pentatonic',
    'peppa',
    'perceptual',
    'percussive',
    'perfected',
    'perforated',
    'perfumed',
    'perilous',
    'periodic',
    'peripheral',
    'perishable',
    'permanent',
    'permissive',
    'pernicious',
    'perpendicular',
    'perpetual',
    'perplexing',
    'persevering',
    'persian',
    'persistent ',
    'personable',
    'personalized',
    'perspicacious',
    'persuasive',
    'pertinent',
    'perturbed',
    'pessimistic',
    'pestilent',
    'pet',
    'petty',
    'petulant',
    'phantasmagorical',
    'phantom',
    'pharaonic',
    'pharmaceutic',
    'phenomenal',
    'philanthropic',
    'philharmonic',
    'philosophic',
    'phlegmatic',
    'phobic',
    'phonetic',
    'phosphorous',
    'photochemical',
    'photoconductive',
    'photogenic',
    'photographic',
    'photosensitive',
    'physical',
    'physiological',
    'piano-playing',
    'picky',
    'picturesque',
    'piercing',
    'piezoelectric',
    'pillared',
    'pirate',
    'pirated',
    'pithy',
    'pitiful',
    'pitiless',
    'pivotal',
    'pixelated',
    'pizzicato',
    'placeable',
    'placid',
    'plagiarised',
    'plain and clear',
    'planar',
    'planetary',
    'planktonic',
    'planned',
    'plastic',
    'platonic',
    'plausible',
    'playable',
    'playful',
    'pleading',
    'pleasant',
    'plenary',
    'plentiful',
    'plucky ',
    'plumaged',
    'plumbing',
    'plumed',
    'pluralistic',
    'plush',
    'plutocratic',
    'pneumatic',
    'pocket',
    'poetic',
    'pointless',
    'poised',
    'poisonous',
    'polar',
    'polarized',
    'polemical',
    'police',
    'polished',
    'polite ',
    'political',
    'polka dot',
    'polluted',
    'polyatomic',
    'polychromatic',
    'polyglot',
    'polymeric',
    'polymorphic',
    'polynomial',
    'polysyllabic',
    'pompous',
    'poor',
    'popping',
    'popular',
    'porous',
    'portable',
    'portly',
    'posh',
    'positional',
    'positive',
    'possessive',
    'possible',
    'postal',
    'postdoctoral',
    'postglacial',
    'postgraduate',
    'postindustrial',
    'potable',
    'potent',
    'potential',
    'powerful ',
    'powerless',
    'practical',
    'pragmatic',
    'praiseworthy',
    'prankish',
    'precautionary',
    'preceding',
    'precious',
    'precipitating',
    'precise',
    'precognitive',
    'preconditioned',
    'precooked',
    'predatory',
    'predestined',
    'predictable',
    'predominant',
    'preeminent',
    'preemptive',
    'prefabricated',
    'preferred',
    'prehistoric',
    'prejudicious',
    'preliminary',
    'premature',
    'premeditated',
    'premiere',
    'premium',
    'preoccupied',
    'prepackaged',
    'prepaid',
    'prepared',
    'prepossessing',
    'preposterous',
    'prerecorded',
    'prescribed',
    'present',
    'presidential',
    'pressing',
    'pressurized',
    'prestigious',
    'presumptive',
    'pretty',
    'prevailing',
    'prevalent',
    'preventable',
    'previous',
    'prewar',
    'priceless',
    'prickly',
    'priestly',
    'primal',
    'primary',
    'prime',
    'primitive',
    'primordial',
    'principal',
    'principled',
    'printable',
    'pristine',
    'private',
    'privileged',
    'prized',
    'prizewinning',
    'probable',
    'problematic',
    'procedural',
    'procreative',
    'productive',
    'profane',
    'professional',
    'professor',
    'proficient ',
    'profitable',
    'profound',
    'prognostic',
    'programmable',
    'progressive',
    'prohibitive',
    'proletarian',
    'prolific',
    'prolonged',
    'prolusory',
    'prominent',
    'promising',
    'promotional',
    'prompt',
    'pronounced',
    'proper',
    'prophetic',
    'prophylactic',
    'propitious ',
    'proportionate',
    'proprietary',
    'propulsive',
    'prosaic',
    'prosperous',
    'prosthetic',
    'prostrate',
    'protective',
    'protein-rich',
    'prototypical',
    'proud',
    'proven',
    'proverbial',
    'provident',
    'provincial',
    'provisionary',
    'provocative',
    'proxy',
    'prudent',
    'pseudo',
    'psychedelic',
    'psychiatric',
    'psychological',
    'psychosomatic',
    'psychotropic',
    'public',
    'published',
    'puffed',
    'pugnacious',
    'pulverised',
    'pumped',
    'punctureless',
    'punishable',
    'puny',
    'pure',
    'purgatorial',
    'purified',
    'purple',
    'purposeful',
    'purposeless',
    'purring',
    'pushy',
    'puzzling',
    'pyramidal',
    'pyromaniac',
    'pyrotechnical',
    'pyrrhic',
    'quack',
    'quacking',
    'quadraphonic',
    'quadratic',
    'quadruped',
    'quadruple',
    'quadruplex',
    'quaggy',
    'quaint',
    'qualified',
    'qualitative',
    'quantitative',
    'quantized',
    'quantum',
    'quarantined',
    'quarrelsome',
    'quarterly',
    'quartz',
    'quasi',
    'quaternary',
    'quemeful',
    'quenched',
    'quenchless',
    'querulous',
    'questionable',
    'quick brown',
    'quick-minded',
    'quick-tempered',
    'quick-witted',
    'quicksilver',
    'quiet',
    'quilted',
    'quintessential',
    'quintuple',
    'quirky',
    'quivering',
    'quixotic',
    'quizzical',
    'quotable',
    'rabid ',
    'radial',
    'radiant ',
    'radical ',
    'radio',
    'radioactive ',
    'radiophobic',
    'ragged',
    'raging',
    'rail',
    'rainbow',
    'rainproof',
    'raising',
    'rakish ',
    'rambling',
    'rambunctious ',
    'rampaging',
    'rampant ',
    'random',
    'rapid',
    'rapturous',
    'rare',
    'rascal',
    'rash',
    'raspy ',
    'rational',
    'ratty ',
    'raucous ',
    'raunchy',
    'ravenous ',
    'raving',
    'ravishing ',
    'raw',
    'reactive',
    'reactor-powered',
    'readable',
    'ready',
    'real',
    'real-time',
    'realistic',
    'reanimated',
    'rearmost',
    'reasonable',
    'reassuring',
    'rebellious ',
    'reborn',
    'recalcitrant ',
    'receding',
    'recent',
    'receptive',
    'recessive',
    'rechargeable',
    'reciprocal',
    'reckless',
    'reclaimable',
    'reclusive',
    'recognizable',
    'recoilless',
    'reconcilable',
    'recondite ',
    'recreational',
    'rectangular',
    'recurring',
    'recursive',
    'recyclable',
    'reddish',
    'redeemable',
    'redheaded',
    'reducible',
    'reductive',
    'redundant',
    'redux',
    'reefy',
    'referential',
    'refillable',
    'refined',
    'reflective ',
    'reflexive',
    'reformatory',
    'refractive',
    'refreshing ',
    'refrigerated',
    'refundable ',
    'refurbished',
    'refutable',
    'regal',
    'regenerating',
    'regional',
    'registered',
    'regressive',
    'regrettable',
    'regular',
    'regulatory',
    'rehabilitative',
    'reincarnate',
    'reinvigorated',
    'rejective',
    'rejoicing',
    'relatable',
    'relative',
    'relativistic',
    'relaxing',
    'relentless',
    'relevant ',
    'reliable ',
    'relieved',
    'reluctant',
    'remarkable ',
    'remedial',
    'reminiscent',
    'remorseless',
    'remote',
    'removable',
    'renewable',
    'renowned',
    'rented',
    'reorganized',
    'repaired',
    'repelling',
    'repetitive',
    'replaceable',
    'replicable',
    'reprehensible ',
    'representative',
    'repressive',
    'reproachful',
    'reptilian',
    'republican',
    'repugnant ',
    'repulsive ',
    'reputed',
    'required',
    'rescued',
    'reserved',
    'resident',
    'residual',
    'resilient ',
    'resin',
    'resistant',
    'resolute',
    'resolved',
    'resonant',
    'resounding',
    'resourceful',
    'resourceless',
    'respectable',
    'respiratory',
    'responsible',
    'responsive',
    'rested',
    'restless ',
    'restrictive',
    'resurgent',
    'retired',
    'retractable',
    'retributive',
    'retrievable',
    'retro',
    'retrospective',
    'returned',
    'reunited',
    'reusable',
    'revamped',
    'revealing',
    'revelatory',
    'revenant',
    'revengeful',
    'reverberant',
    'reverent',
    'revertible',
    'revitalising',
    'revocable',
    'revolting',
    'revolutionary',
    'rewarding',
    'rhapsodic',
    'rhetorical ',
    'rhomboid',
    'rhythmic',
    'rich ',
    'rickrolled',
    'ridiculously',
    'right-handed',
    'righteous',
    'rightful',
    'rigid ',
    'rigorous ',
    'rimmed',
    'ringing',
    'ripe ',
    'rising',
    'risk-free',
    'risky ',
    'ritual',
    'rival',
    'roaring',
    'roasted',
    'robotic',
    'robust ',
    'rocket-propelled',
    'rogue-like',
    'roguish',
    'roily',
    'role-playing',
    'rolling',
    'romantic ',
    'roofless',
    'roomy ',
    'root',
    'rooted',
    'rosy ',
    'rotary',
    'rotatory',
    'rough ',
    'round ',
    'rousing ',
    'routine ',
    'royal',
    'rubber',
    'ruddy ',
    'rude ',
    'rudimentary ',
    'rugged ',
    'ruinous',
    'ruling',
    'rumbling',
    'runic',
    'ruptured',
    'rural',
    'rushing',
    'rustic ',
    'rustproof',
    'rusty ',
    'ruthless ',
    'sabertoothed',
    'sabotaged',
    'sacred',
    'sacrificial',
    'sacrosanct',
    'sad',
    'safe',
    'sage',
    'sailor',
    'saintly',
    'salable',
    'salient',
    'salty',
    'salubrious',
    'salutary',
    'salvageable',
    'same',
    'sanative',
    'sanctimonious',
    'sandy',
    'sane',
    'sanguine',
    'sanitary',
    'sapient',
    'sapless',
    'sapphire',
    'sappy',
    'sarcastic',
    'sardonic',
    'sartorial',
    'sassy',
    'satellite',
    'satin',
    'satinated',
    'satirical',
    'satisfactory',
    'satisfied',
    'saturated',
    'savage',
    'savory',
    'savvy',
    'scalable',
    'scalar',
    'scaly',
    'scarce',
    'scared',
    'scarlet',
    'scary',
    'scathing',
    'scenic',
    'scented',
    'scentless',
    'sceptical',
    'scheduled',
    'schematic',
    'scholar',
    'scientific',
    'scintillating',
    'sclerotic',
    'scorching',
    'scornful',
    'scratchy',
    'scrawny',
    'screaming',
    'screeching',
    'scrubbed',
    'scruffy',
    'scrupulous',
    'sculpted',
    'scummy',
    'scurvy',
    'sea-faring',
    'sealed',
    'seamless',
    'searching',
    'searing',
    'seasick',
    'seasoned',
    'seaworthy',
    'secluded',
    'secondary',
    'secret',
    'secretive',
    'sectarian',
    'sectorial',
    'secure',
    'security',
    'sedative',
    'sedimentary',
    'seedy',
    'segmented',
    'seismic',
    'select',
    'selective',
    'self-absorbed',
    'self-confident ',
    'self-explanatory',
    'self-fulfilling',
    'self-reliant',
    'self-sufficient',
    'selfish',
    'selfless',
    'semiannual',
    'semiautomatic',
    'semiconducting',
    'semimonthly',
    'semiterrestrial',
    'semitransparent',
    'senior',
    'sensational',
    'senseless',
    'sensible ',
    'sensitive',
    'sensual',
    'sentient',
    'sentimental',
    'separable',
    'sequential',
    'serendipitous',
    'serene',
    'serial',
    'serious',
    'serpentine',
    'serviceable',
    'settled',
    'sevenfold',
    'seventh',
    'severe',
    'shabby',
    'shadowy',
    'shady',
    'shaggy',
    'shaky',
    'shallow',
    'shaman',
    'shame of',
    'shameful',
    'shameless',
    'shapeless',
    'shapely',
    'sharp',
    'sharp-pointed',
    'shattering',
    'sheepish',
    'sheer',
    'sheltered',
    'shimmering',
    'shining',
    'shiny',
    'shivering',
    'shocking',
    'shoeless',
    'short',
    'short-haired',
    'shredded',
    'shrewd',
    'shrieking',
    'shrinkable',
    'shy',
    'siamese',
    'sickening',
    'sidearm',
    'sideways',
    'signal',
    'significant',
    'silent',
    'silky',
    'silly',
    'silver',
    'similar',
    'simple',
    'simpleminded',
    'simplified',
    'simplistic',
    'simulated',
    'simultaneous',
    'sincere ',
    'sinewy',
    'singing',
    'single',
    'singular',
    'sinister',
    'sinkable',
    'sinusoidal',
    'sith',
    'sitting',
    'sizable',
    'skeletal',
    'skeptical',
    'sketch of a',
    'skewed',
    'skillful',
    'skimmed',
    'skinny',
    'skyward',
    'slapstick',
    'sleazy',
    'sleek ',
    'sleepless',
    'sleepy',
    'sleeveless',
    'slender',
    'slick',
    'sliding',
    'slightly',
    'slim',
    'slimy',
    'slippery',
    'slow',
    'sluggish',
    'sly',
    'small',
    'smart',
    'smashing',
    'smelly',
    'smiling',
    'smitten',
    'smoggy',
    'smoked',
    'smoldering',
    'smooth',
    'snappy',
    'sneaky',
    'sneezing',
    'sneezy',
    'sniffy',
    'snobbish',
    'snooty',
    'snoring',
    'snow-white',
    'snugly',
    'soapy',
    'soaring',
    'sober',
    'sociable',
    'social',
    'societal',
    'socratic',
    'soft',
    'softhearted',
    'solar',
    'solemn',
    'solicitous',
    'solid',
    'solitary',
    'soluble',
    'something like',
    'sometimes',
    'sonorous',
    'soothing',
    'sophisticated',
    'sordid',
    'sorrowful',
    'soulless',
    'sound',
    'soundproof',
    'sour',
    'southeast',
    'southern',
    'southwest',
    'sovereign',
    'space',
    'spacious',
    'spare',
    'sparing',
    'sparkling ',
    'sparse',
    'spartan',
    'spatial',
    'speaking',
    'special',
    'specific',
    'speckled',
    'spectacular ',
    'spectral',
    'speculative',
    'speechless',
    'spellbound',
    'spherical',
    'spicy',
    'spinal',
    'spineless',
    'spiral',
    'spiritual',
    'spiteful',
    'splashy',
    'splendid ',
    'splintered',
    'splitting',
    'spoiled',
    'spongy',
    'spontaneous',
    'spooky',
    'sporadic',
    'sport racing',
    'spotless',
    'spotted',
    'sprightly',
    'springlike',
    'spry',
    'spy',
    'squalid',
    'squandered',
    'square',
    'squashy',
    'squatting',
    'squeaky',
    'squeezable',
    'squishy',
    'stable',
    'staggering',
    'stagnant',
    'stainless',
    'stale',
    'stalemated',
    'stalwart',
    'standard',
    'standing',
    'star',
    'star-crossed',
    'starboard',
    'staring',
    'stark',
    'starlit',
    'startling',
    'starving',
    'stately',
    'statewide',
    'static',
    'stationary',
    'statistical',
    'statutory',
    'staunch',
    'steadfast',
    'steady',
    'stealthy',
    'steel',
    'steep',
    'stellar ',
    'stentorian',
    'stereoscopic',
    'stereotypic',
    'sterile',
    'stewed',
    'sticky',
    'stiff',
    'still',
    'stinging',
    'stingy',
    'stinky',
    'stochastic',
    'stock',
    'stocky',
    'stoic',
    'stone',
    'stone-hearted',
    'stormproof',
    'stormy',
    'stout',
    'straightforward',
    'strained',
    'stranded',
    'strange',
    'strategic',
    'stratified',
    'straw',
    'stray',
    'streamlined',
    'street',
    'strenuous',
    'stressful',
    'stretchy',
    'strict',
    'striking',
    'striped',
    'strong',
    'struggling',
    'stubborn',
    'stuffed',
    'stunning ',
    'stupendous ',
    'sturdy',
    'stuttering',
    'stylish',
    'stylized',
    'suave',
    'sub-culture',
    'subalpine',
    'subatomic',
    'subconscious',
    'subjective',
    'sublimated',
    'sublime',
    'submarine',
    'submersible',
    'suboceanic',
    'subordinated',
    'subscript',
    'subsequent',
    'substantial',
    'subterranean',
    'subtle',
    'subtropic',
    'suburban',
    'successful',
    'suddenly',
    'sufferable',
    'sufficient',
    'sugar',
    'sugar-sweet',
    'suggestive',
    'suitable',
    'sulfuric',
    'sumptuous',
    'sunburned',
    'sunken',
    'sunny',
    'sunstruck',
    'suntanned',
    'super ',
    'superb',
    'supercritical',
    'superficial',
    'superhuman',
    'superior',
    'supernatural',
    'superscript',
    'supersonic',
    'superstitious',
    'supperless',
    'supplementary',
    'supportive',
    'supposed',
    'suppressive',
    'supreme',
    'surface',
    'surgical',
    'surmountable',
    'surpassing',
    'surplus',
    'surprising',
    'surreal',
    'surrounding',
    'survivable',
    'susceptible',
    'suspected',
    'suspicious',
    'sustainable',
    'swampy',
    'sweaty',
    'sweeping',
    'sweet',
    'sweetheart',
    'swift',
    'swimming',
    'swinging',
    'swiss army',
    'swollen',
    'swooping',
    'symbiotic',
    'symbolic',
    'symmetric',
    'sympathetic',
    'symphonic',
    'symptomatic',
    'symptomless',
    'synaptic',
    'synchronous',
    'synergetic',
    'synonymous',
    'synoptic',
    'synthetic',
    'systematic',
    'tabby',
    'taboo',
    'tabular',
    'taciturn',
    'tacky',
    'tactful',
    'tactical',
    'tactile',
    'tactless',
    'tailless',
    'tailored',
    'tainted',
    'talented',
    'talkative',
    'tall',
    'taloned',
    'tamable',
    'tangential',
    'tangible',
    'tangled',
    'tanned',
    'tantalizing',
    'tantamount',
    'tapered',
    'tardy',
    'targeted',
    'tarnished',
    'tasmanian',
    'tasseled',
    'tasteful',
    'tasteless',
    'tasty',
    'tattered',
    'taunting',
    'tawdry',
    'taxable',
    'taxing',
    'teachable',
    'tearful',
    'tearing',
    'tearless',
    'teaser',
    'technological',
    'technophobic',
    'tectonic',
    'tedious',
    'teeming',
    'teenage',
    'teeny-tiny',
    'teetotal',
    'teflon',
    'telegraphic',
    'telekinetic',
    'telepathic',
    'telephonic',
    'telescopic',
    'telltale',
    'temperamental',
    'temperate',
    'tempered',
    'temporal',
    'temporary',
    'tempting',
    'tenacious',
    'tender',
    'tenderhearted',
    'tenfold',
    'tenor',
    'tense',
    'tentacled',
    'tentative',
    'tepid',
    'terminal',
    'terminator',
    'terrestrial',
    'terrible',
    'terrific',
    'terrifying',
    'territorial',
    'terse',
    'tessellated',
    'testamentary',
    'tested',
    'testimonial',
    'testy',
    'tetragonal',
    'teutonic',
    'textbook',
    'textile',
    'thankful',
    'thankless',
    'the only sane',
    'the worst',
    'theatrical',
    'thematic',
    'theocratic',
    'theoretical',
    'therapeutic',
    'thermal',
    'thermodynamic',
    'thermonuclear',
    'thermoplastic',
    'thermostatic',
    'thick-skinned',
    'thickened',
    'thickheaded',
    'thin',
    'thinking',
    'thinned',
    'thirsty',
    'thornless',
    'thorny',
    'thorough',
    'thought-provoking ',
    'thoughtful ',
    'thoughtless',
    'thrashed',
    'threatening',
    'three-dimensional',
    'three-headed',
    'threefold',
    'thrilled',
    'thrilling',
    'thriving',
    'thunderous',
    'ticking',
    'ticklish',
    'tidal',
    'tidy',
    'tight-lipped',
    'tightfisted',
    'tillable',
    'timber',
    'time-saving',
    'timeless',
    'timely',
    'timeworn',
    'timid',
    'timorous',
    'tiny',
    'tipsy',
    'tiptop',
    'tired',
    'tireless',
    'tiresome',
    'tiring',
    'titanic',
    'titular',
    'toeless',
    'tolerable',
    'tonal',
    'tone-deaf',
    'tongueless',
    'toothless',
    'toothy',
    'top-notch',
    'topless',
    'topographic',
    'topological',
    'tormenting',
    'tornado',
    'toroidal',
    'torpid',
    'torrential',
    'torrid',
    'tortuous',
    'total',
    'totalitarian',
    'totemic',
    'touching',
    'tough',
    'tourist',
    'towering',
    'toxic',
    'toy',
    'trackless',
    'tractable',
    'traditional',
    'tragic',
    'tragicomic',
    'trained',
    'traitorous',
    'tranquil',
    'tranquilizing',
    'transatlantic',
    'transcendent',
    'transcontinental',
    'transferable',
    'transformational',
    'transitory',
    'translatable',
    'translucent',
    'transmittable',
    'transnational',
    'transoceanic',
    'transparent',
    'transpiring',
    'transportable',
    'transuranic',
    'trapped',
    'trashed',
    'traumatic',
    'traveling',
    'traversable',
    'treacherous',
    'treasonous',
    'treasured',
    'treelike',
    'tremendous',
    'trenchant',
    'trendsetting',
    'trendy',
    'trepid',
    'triangular',
    'tribal',
    'trichromatic',
    'tricky',
    'tricolor',
    'trifling',
    'trigonometric',
    'trilingual',
    'trim',
    'tripedal',
    'triplex',
    'triploid',
    'tripping',
    'triumphal',
    'trivial',
    'trojan',
    'tropical',
    'troubled',
    'troublesome',
    'truant',
    'truculent',
    'true',
    'true neutral',
    'truehearted',
    'truncate',
    'truncated',
    'trusting',
    'trustworthy',
    'trusty',
    'trying',
    'trying to be',
    'tubed',
    'tubular',
    'tuneless',
    'turbid',
    'turbulent',
    'turgid',
    'turn-based',
    'tusked',
    'tutorial',
    'twice removed',
    'twilight',
    'twin',
    'twinkling ',
    'twisted',
    'two-dimensional',
    'two-faced',
    'two-factor',
    'twofold',
    'typical',
    'typographic',
    'tyrannical',
    'uber ',
    'ubiquitous ',
    'ugliest',
    'ulterior ',
    'ultimate ',
    'ultra ',
    'ultramarine',
    'ultramodern',
    'ultrasonic ',
    'ultraviolet',
    'unacceptable',
    'unaccompanied',
    'unaccountable',
    'unachievable',
    'unacknowledged',
    'unadapted',
    'unadjustable',
    'unadoptable',
    'unadventurous',
    'unadvisable',
    'unaesthetic',
    'unaffectionate',
    'unaffiliated',
    'unaffordable',
    'unaided',
    'unalienable',
    'unaltered',
    'unambiguous',
    'unambitious',
    'unannounced',
    'unanswered ',
    'unanticipated',
    'unapologetic',
    'unappealing',
    'unappeasable',
    'unappetizing ',
    'unappreciated',
    'unapproachable',
    'unarmed',
    'unarmored',
    'unarticulated',
    'unashamed',
    'unassigned',
    'unassisted',
    'unattached',
    'unattackable',
    'unattainable',
    'unauthentic',
    'unauthorized',
    'unavailable',
    'unavoidable',
    'unaware',
    'unawed',
    'unbearable ',
    'unbeatable ',
    'unbelievable ',
    'unbending',
    'unbiased',
    'unblemished',
    'unblinking',
    'unbound',
    'unbreakable',
    'unburdened',
    'uncanny ',
    'uncapped',
    'unceremonious',
    'uncertain',
    'uncertified',
    'unchained',
    'unchallenged',
    'unchanging',
    'uncharacteristic',
    'uncharted',
    'unchecked',
    'unchewable',
    'uncivil',
    'uncivilized',
    'unclaimed',
    'unclassified',
    'unclean ',
    'uncluttered',
    'uncombined',
    'uncomfortable',
    'uncommitted',
    'uncommon',
    'uncommunicative',
    'uncompensated',
    'uncomplaining',
    'uncompromising',
    'unconditional',
    'unconfined',
    'unconfirmed',
    'unconnected',
    'unconquerable',
    'unconscious',
    'unconsidered',
    'unconsolidated',
    'unconstitutional',
    'unconstrained',
    'unconsumed',
    'uncontested',
    'uncontrollable',
    'unconventional',
    'unconvinced',
    'uncooked',
    'uncool',
    'uncooperative',
    'uncoordinated',
    'uncorrectable',
    'uncorrelated',
    'uncorrupted',
    'uncountable',
    'uncovered',
    'uncultured',
    'uncured',
    'uncut',
    'undamaged',
    'undead',
    'undeceived',
    'undecided',
    'undecipherable',
    'undeclared',
    'undefeatable',
    'undefendable',
    'undefined',
    'undemanding',
    'undeniable',
    'under',
    'underage',
    'underbred',
    'underclass',
    'underclothed',
    'undercooked',
    'undercover',
    'underfed',
    'underfunded',
    'underground',
    'undermentioned',
    'undernourished',
    'underqualified',
    'underrated ',
    'undersized',
    'understandable',
    'underwater',
    'underweight ',
    'undescriptive',
    'undeserved',
    'undesigned',
    'undestroyable',
    'undetectable',
    'undetermined',
    'undeviating',
    'undigested',
    'undiminished',
    'undiplomatic ',
    'undisciplined',
    'undiscovered',
    'undisputable',
    'undistinguished',
    'undistorted',
    'undisturbed',
    'undivided',
    'undoable',
    'undomesticated',
    'undrinkable',
    'undying ',
    'unearthly',
    'uneasy ',
    'uneatable',
    'uneconomic',
    'unedited',
    'uneducated',
    'unemotional',
    'unemphatic',
    'unemployed',
    'unencumbered',
    'unending',
    'unendurable',
    'unenforceable',
    'unenlightened',
    'unenthusiastic',
    'unenviable ',
    'unequaled',
    'unequivocal',
    'unethical',
    'uneven',
    'unexcelled',
    'unexchangeable',
    'unexcited',
    'unexpected ',
    'unexpired',
    'unexplainable',
    'unexploded',
    'unexplored',
    'unexpressive',
    'unfading',
    'unfailing',
    'unfair',
    'unfamiliar',
    'unfashionable',
    'unfathomable',
    'unfavorable',
    'unfeasible',
    'unfinished',
    'unfit',
    'unfixable',
    'unflappable ',
    'unforeseeable',
    'unforgettable',
    'unforgivable',
    'unfortunate ',
    'unfriendly ',
    'unfunny',
    'ungainly ',
    'ungovernable',
    'ungracious ',
    'ungrateful ',
    'unhappy ',
    'unharmed',
    'unhatched',
    'unhealthy',
    'unhelpful',
    'unhurried ',
    'unhurt',
    'unidentifiable',
    'unidentified flying',
    'unidirectional',
    'unified',
    'uniform',
    'unilateral',
    'unimaginable ',
    'unimportant ',
    'unimpressed',
    'unimprisoned',
    'uninfected',
    'uninfluential',
    'uninformative',
    'uninhabited',
    'uninquisitive',
    'uninspiring',
    'unintelligible',
    'unintentional',
    'uninterested',
    'uninterrupted',
    'unintimidated',
    'uninventive',
    'uninvited',
    'uninvolved',
    'unipolar',
    'unique ',
    'united ',
    'universal',
    'univocal',
    'unjust ',
    'unjustified',
    'unkempt',
    'unkind ',
    'unknowable',
    'unknowledgeable',
    'unknown',
    'unlabeled',
    'unlawful',
    'unlicenced',
    'unlikeable',
    'unlimited',
    'unlit',
    'unlocked',
    'unlovely',
    'unlucky',
    'unmanageable',
    'unmanned',
    'unmarked',
    'unmarketable',
    'unmasked',
    'unmatched',
    'unmemorable',
    'unmentionable',
    'unmerciful',
    'unmistakable',
    'unmodified',
    'unmotivated ',
    'unmovable',
    'unnameable',
    'unnatural',
    'unnecessary ',
    'unnerving ',
    'unnoticeable',
    'unobjectionable',
    'unobserved',
    'unobstructed',
    'unobtainable',
    'unoccupied ',
    'unofficial',
    'unordered',
    'unorganized',
    'unoriginal',
    'unorthodox',
    'unpackaged',
    'unpaid',
    'unpaintable',
    'unpalatable',
    'unparalleled',
    'unpardonable',
    'unpartitioned',
    'unpassable',
    'unpatented',
    'unperceivable',
    'unpersuasive',
    'unpictured',
    'unplanned',
    'unplayable',
    'unpleasant',
    'unplumbed',
    'unpolished',
    'unpopular ',
    'unprecedented',
    'unpredictable ',
    'unprepared',
    'unpreventable',
    'unprintable',
    'unprocurable',
    'unproductive',
    'unprofessional',
    'unprofitable',
    'unpronounceable',
    'unprotected',
    'unproven',
    'unprovoked',
    'unpublished',
    'unpunished',
    'unqualified',
    'unquenchable',
    'unquestionable',
    'unquotable',
    'unranked',
    'unreachable',
    'unreadable',
    'unreal ',
    'unrealistic',
    'unreasonable ',
    'unrecognized',
    'unrecorded',
    'unrecoverable',
    'unredeemable',
    'unrefined',
    'unregenerated',
    'unregistered',
    'unregulated',
    'unrelated',
    'unrelaxed',
    'unrelenting',
    'unrelieved',
    'unremarkable',
    'unrepeatable',
    'unreplaceable',
    'unrepresentative',
    'unrequested',
    'unresistant',
    'unresponsive',
    'unrestricted',
    'unrewarding',
    'unrivaled',
    'unruly',
    'unsaddled',
    'unsafe ',
    'unsaid',
    'unsaleable',
    'unsalvageable',
    'unsatisfied',
    'unscalable',
    'unscheduled',
    'unsealed',
    'unseasoned',
    'unsecured',
    'unseen',
    'unselfish',
    'unsentimental',
    'unsettling',
    'unshaken',
    'unshockable',
    'unshrinking',
    'unsightly',
    'unsigned',
    'unsilenced',
    'unsinkable',
    'unskillful',
    'unsoiled',
    'unsold',
    'unsolicited',
    'unsolved',
    'unsorted',
    'unsparing',
    'unspeakable',
    'unspecified',
    'unspent',
    'unspoiled',
    'unstable',
    'unstaged',
    'unstained',
    'unsteady',
    'unstoppable',
    'unstructured',
    'unstudied',
    'unsubstantial',
    'unsuccessful',
    'unsuitable',
    'unsung',
    'unsupportive',
    'unsurprising',
    'unsuspected',
    'unsustainable',
    'unsymmetrical',
    'untainted',
    'untalented ',
    'untamed',
    'untanned',
    'untested',
    'unthankful',
    'unthinkable',
    'untidy ',
    'untitled',
    'untold',
    'untouchable',
    'untraceable',
    'untrained',
    'untransferable',
    'untranslatable',
    'untraveled',
    'untreated',
    'untroubled',
    'untrue',
    'untrustworthy',
    'untruthful',
    'untutored',
    'untypical',
    'unusable',
    'unused ',
    'unusual ',
    'unutterable',
    'unvaccinated',
    'unvanquishable',
    'unvarying ',
    'unverified',
    'unvoiced',
    'unwanted',
    'unwarranted',
    'unwary ',
    'unwashed',
    'unwearable',
    'unwelcome',
    'unwilling ',
    'unwise',
    'unworthy',
    'unwritten',
    'unyielding ',
    'up-to-date',
    'upbeat ',
    'upcoming ',
    'upfront ',
    'uphill ',
    'uplifted ',
    'upper-class',
    'upright ',
    'upscale ',
    'upset',
    'upstage ',
    'upstairs ',
    'upstanding ',
    'upstart ',
    'upstream ',
    'uptight ',
    'uptown',
    'upward ',
    'upwind ',
    'urban ',
    'urgent ',
    'ursine',
    'usable',
    'useful',
    'useless',
    'user-friendly',
    'usual',
    'utilitarian',
    'utmost ',
    'utopian',
    'utter',
    'vacant ',
    'vacuous ',
    'vagabond ',
    'vagrant',
    'vague',
    'vainglorious ',
    'valiant ',
    'valid',
    'valorous ',
    'valued',
    'vampiric',
    'vandalous ',
    'vanquished',
    'vaporous ',
    'variable ',
    'variant of',
    'varying',
    'vast ',
    'vaulted',
    'vector',
    'vegetarian ',
    'vegetative',
    'vehement ',
    'vehicular',
    'veiled',
    'velvet',
    'venerable ',
    'vengeful',
    'venomous ',
    'veracious ',
    'verbal',
    'verbatim',
    'verbose ',
    'verdant ',
    'verified',
    'verminous',
    'versatile ',
    'vertebral',
    'vertical ',
    'vested',
    'vestibular',
    'veteran',
    'veterinary',
    'vexatious ',
    'vexed',
    'viable ',
    'vibrant ',
    'vicious ',
    'victimized',
    'victorian',
    'victorious ',
    'vigilant',
    'vigorous ',
    'viking',
    'vile',
    'villainous ',
    'vindictive ',
    'violent ',
    'violet',
    'viral',
    'virtual',
    'virtuous ',
    'viscous ',
    'visible',
    'visual ',
    'vital ',
    'vitalizing',
    'vitreous ',
    'vitriolic ',
    'vivacious ',
    'vivid ',
    'vocal',
    'vocational',
    'vocative',
    'vociferous ',
    'voiceless',
    'void',
    'volatile',
    'volcanic ',
    'volumetric',
    'voluminous ',
    'volunteering',
    'voodoo',
    'voracious ',
    'vulcanized',
    'vulnerable ',
    'wacky ',
    'wailing',
    'waiting',
    'waking up',
    'walking',
    'wandering',
    'wanted',
    'wanton ',
    'warm ',
    'warm-blooded',
    'warmhearted ',
    'warming',
    'warning',
    'warped ',
    'wary ',
    'washable',
    'wasteful ',
    'watchful',
    'water-cooled',
    'waterborne',
    'waterlogged',
    'waterproof',
    'watertight',
    'watery',
    'wavy',
    'waxy ',
    'wayward ',
    'wealthy ',
    'weaponized',
    'wearisome ',
    'weary ',
    'weathered ',
    'wee ',
    'weedy',
    'week-long',
    'weekly',
    'weepy ',
    'weightless',
    'weighty',
    'weird',
    'welcoming ',
    'well oiled',
    'well-adjusted',
    'well-balanced',
    'well-behaving',
    'well-built',
    'well-commented',
    'well-developed',
    'well-documented',
    'well-dressed',
    'well-educated',
    'well-equipped',
    'well-fit',
    'well-informed',
    'well-known',
    'well-made',
    'well-maintained',
    'well-mannered',
    'well-placed',
    'well-planned',
    'well-prepared',
    'well-preserved',
    'well-read',
    'well-received',
    'well-traveled',
    'well-written',
    'western',
    'wet ',
    'whimsical ',
    'whiny ',
    'whispering',
    'whistling',
    'white ',
    'wholehearted ',
    'wholesome ',
    'whopping ',
    'wicked ',
    'wide',
    'wide-eyed',
    'widespread ',
    'wiggly',
    'wild ',
    'willing ',
    'willowy ',
    'wily ',
    'wimpy ',
    'winding ',
    'windswept ',
    'windy ',
    'winking',
    'winning ',
    'winsome ',
    'winter',
    'wireless',
    'wiry ',
    'wise ',
    'wispy ',
    'wistful ',
    'withdrawn ',
    'withering ',
    'witty ',
    'wizardly',
    'wobbly ',
    'woebegone ',
    'woeful',
    'wonderful ',
    'wondrous ',
    'wonky ',
    'wooden',
    'woozy ',
    'work-oriented',
    'worker',
    'world wide',
    'worldly ',
    'worn-down',
    'worn-out',
    'worried',
    'worrisome ',
    'worst',
    'worthless ',
    'worthwhile ',
    'wounded ',
    'wounding',
    'wrathful',
    'wretched ',
    'wriggly',
    'wrinkled',
    'wrong ',
    'wry ',
    'xenolithic ',
    'xenomorphous',
    'yappy ',
    'yawning ',
    'year-round',
    'yearly ',
    'yelling',
    'yellow-bellied',
    'yelping ',
    'yesterdays',
    'yodeling ',
    'yoga',
    'yoked ',
    'yokeless ',
    'yokelish ',
    'yonder ',
    'young-at-heart',
    'young-looking',
    'your friend',
    'youthful ',
    'yowling ',
    'yucky ',
    'yummy ',
    'zaftig',
    'zany',
    'zappy',
    'zealous',
    'zen',
    'zestful ',
    'zigzag',
    'zinc-coated',
    'zingy',
    'zippy',
    'zodiacal',
    'zombielike',
    'zonked',
    'zoomed in',
    'zoomy',
  ];
}
