/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { NativeProxy, NativeProxyInterface } from "../NativeProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "nftAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nftPrice",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class NativeProxy__factory {
  static readonly abi = _abi;
  static createInterface(): NativeProxyInterface {
    return new utils.Interface(_abi) as NativeProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NativeProxy {
    return new Contract(address, _abi, signerOrProvider) as NativeProxy;
  }
}
