compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    
    

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs

yarnPath: .yarn/releases/yarn-4.1.0.cjs
