import { userWalletLoginWithoutChecks, updateBackendUri, getRemoteBackendVersion } from '@paima/sdk/mw-core';
declare const endpoints: {
    createLobby: (numberOfRounds: number, roundLength: number, playTimePerPlayer: number, botDifficulty: number, isHidden?: boolean, isPractice?: boolean, playerOneIsWhite?: boolean) => Promise<import("./types").CreateLobbySuccessfulResponse | import("@paima/utils").FailedResult>;
    joinLobby: (lobbyID: string) => Promise<import("@paima/utils").OldResult>;
    closeLobby: (lobbyID: string) => Promise<import("@paima/utils").OldResult>;
    submitMoves: (lobbyID: string, roundNumber: number, move: import("@chess/game-logic").MatchMove) => Promise<import("@paima/utils").FailedResult | import("./types").PackedLobbyState>;
    getUserStats: (walletAddress: string) => Promise<import("./types").PackedUserStats | import("@paima/utils").FailedResult>;
    getLobbyState: (lobbyID: string) => Promise<import("./types").PackedLobbyState | import("@paima/utils").FailedResult>;
    getLobbySearch: (wallet: string, searchQuery: string, page: number, count?: number) => Promise<import("./types").LobbyStates | import("@paima/utils").FailedResult>;
    getRoundExecutionState: (lobbyID: string, round: number) => Promise<import("./types").PackedRoundExecutionState | import("@paima/utils").FailedResult>;
    getRandomOpenLobby: () => Promise<import("./types").PackedLobbyState | import("@paima/utils").FailedResult>;
    getOpenLobbies: (wallet: string, page: number, count?: number) => Promise<import("./types").LobbyStates | import("@paima/utils").FailedResult>;
    getUserLobbiesMatches: (walletAddress: string, page: number, count?: number) => Promise<import("./types").PackedUserLobbies | import("@paima/utils").FailedResult>;
    getNewLobbies: (wallet: string, blockHeight: number) => Promise<import("./types").NewLobbies | import("@paima/utils").FailedResult>;
    getMatchWinner: (lobbyId: string) => Promise<import("@paima/utils").Result<import("@chess/utils").MatchWinnerResponse>>;
    getRoundExecutor: (lobbyId: string, roundNumber: number) => Promise<import("@paima/utils").Result<import("@paima/executors").RoundExecutor<import("@chess/game-logic").MatchState, import("@chess/game-logic").TickEvent>>>;
    getMatchExecutor: (lobbyId: string) => Promise<import("@paima/utils").Result<import("@paima/executors").MatchExecutor<import("@chess/game-logic").MatchState, import("@chess/game-logic").TickEvent>>>;
    exportLogs: () => string;
    pushLog: (message: any, ...optionalParams: any[]) => void;
    getLatestProcessedBlockHeight: () => Promise<import("@paima/utils").Result<number>>;
    userWalletLogin: (loginInfo: import("@paima/mw-core/build/types").LoginInfo, setDefault?: boolean) => Promise<import("@paima/utils").Result<import("@paima/sdk/mw-core").Wallet>>;
    checkWalletStatus: () => Promise<import("@paima/utils").OldResult>;
};
export * from './types';
export type * from './types';
export { userWalletLoginWithoutChecks, updateBackendUri, getRemoteBackendVersion };
export default endpoints;
